// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const consumePasswordResetToken = `-- name: ConsumePasswordResetToken :exec
UPDATE password_reset_tokens SET used_at = now() WHERE id = $1 AND used_at IS NULL
`

func (q *Queries) ConsumePasswordResetToken(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, consumePasswordResetToken, id)
	return err
}

const createPasswordResetToken = `-- name: CreatePasswordResetToken :one
INSERT INTO password_reset_tokens (user_id, token_hash, expires_at)
VALUES ($1, $2, $3)
RETURNING id, user_id, token_hash, expires_at, used_at, created_at
`

type CreatePasswordResetTokenParams struct {
	UserID    uuid.UUID          `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

// ── Password reset tokens ─────────────────────────────────────
func (q *Queries) CreatePasswordResetToken(ctx context.Context, arg CreatePasswordResetTokenParams) (PasswordResetToken, error) {
	row := q.db.QueryRow(ctx, createPasswordResetToken, arg.UserID, arg.TokenHash, arg.ExpiresAt)
	var i PasswordResetToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createRefreshToken = `-- name: CreateRefreshToken :one
INSERT INTO refresh_tokens (user_id, token_hash, family_id, user_agent, ip_address, expires_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, token_hash, family_id, user_agent, ip_address, expires_at, revoked_at, created_at
`

type CreateRefreshTokenParams struct {
	UserID    uuid.UUID          `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	FamilyID  uuid.UUID          `json:"family_id"`
	UserAgent *string            `json:"user_agent"`
	IpAddress *string            `json:"ip_address"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

// ── Refresh tokens (opaque, hashed, rotated; §9.1) ────────────
func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, createRefreshToken,
		arg.UserID,
		arg.TokenHash,
		arg.FamilyID,
		arg.UserAgent,
		arg.IpAddress,
		arg.ExpiresAt,
	)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.FamilyID,
		&i.UserAgent,
		&i.IpAddress,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteExpiredIdempotencyKeys = `-- name: DeleteExpiredIdempotencyKeys :exec
DELETE FROM idempotency_keys WHERE expires_at < now()
`

func (q *Queries) DeleteExpiredIdempotencyKeys(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredIdempotencyKeys)
	return err
}

const getIdempotencyKey = `-- name: GetIdempotencyKey :one
SELECT id, user_id, idem_key, request_hash, status_code, response_body, created_at, expires_at FROM idempotency_keys WHERE user_id = $1 AND idem_key = $2
`

type GetIdempotencyKeyParams struct {
	UserID  uuid.UUID `json:"user_id"`
	IdemKey string    `json:"idem_key"`
}

// ── Idempotency keys (§8.1) ───────────────────────────────────
func (q *Queries) GetIdempotencyKey(ctx context.Context, arg GetIdempotencyKeyParams) (IdempotencyKey, error) {
	row := q.db.QueryRow(ctx, getIdempotencyKey, arg.UserID, arg.IdemKey)
	var i IdempotencyKey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.IdemKey,
		&i.RequestHash,
		&i.StatusCode,
		&i.ResponseBody,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getPasswordResetToken = `-- name: GetPasswordResetToken :one
SELECT id, user_id, token_hash, expires_at, used_at, created_at FROM password_reset_tokens WHERE token_hash = $1
`

func (q *Queries) GetPasswordResetToken(ctx context.Context, tokenHash string) (PasswordResetToken, error) {
	row := q.db.QueryRow(ctx, getPasswordResetToken, tokenHash)
	var i PasswordResetToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getRefreshTokenByHash = `-- name: GetRefreshTokenByHash :one
SELECT id, user_id, token_hash, family_id, user_agent, ip_address, expires_at, revoked_at, created_at FROM refresh_tokens WHERE token_hash = $1
`

func (q *Queries) GetRefreshTokenByHash(ctx context.Context, tokenHash string) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, getRefreshTokenByHash, tokenHash)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.FamilyID,
		&i.UserAgent,
		&i.IpAddress,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const putIdempotencyKey = `-- name: PutIdempotencyKey :one
INSERT INTO idempotency_keys (user_id, idem_key, request_hash, status_code, response_body, expires_at)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (user_id, idem_key) DO NOTHING
RETURNING id, user_id, idem_key, request_hash, status_code, response_body, created_at, expires_at
`

type PutIdempotencyKeyParams struct {
	UserID       uuid.UUID          `json:"user_id"`
	IdemKey      string             `json:"idem_key"`
	RequestHash  string             `json:"request_hash"`
	StatusCode   int32              `json:"status_code"`
	ResponseBody []byte             `json:"response_body"`
	ExpiresAt    pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) PutIdempotencyKey(ctx context.Context, arg PutIdempotencyKeyParams) (IdempotencyKey, error) {
	row := q.db.QueryRow(ctx, putIdempotencyKey,
		arg.UserID,
		arg.IdemKey,
		arg.RequestHash,
		arg.StatusCode,
		arg.ResponseBody,
		arg.ExpiresAt,
	)
	var i IdempotencyKey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.IdemKey,
		&i.RequestHash,
		&i.StatusCode,
		&i.ResponseBody,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const revokeAllUserRefreshTokens = `-- name: RevokeAllUserRefreshTokens :exec
UPDATE refresh_tokens SET revoked_at = now() WHERE user_id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeAllUserRefreshTokens(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeAllUserRefreshTokens, userID)
	return err
}

const revokeRefreshFamily = `-- name: RevokeRefreshFamily :exec
UPDATE refresh_tokens SET revoked_at = now() WHERE family_id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeRefreshFamily(ctx context.Context, familyID uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeRefreshFamily, familyID)
	return err
}

const revokeRefreshToken = `-- name: RevokeRefreshToken :exec
UPDATE refresh_tokens SET revoked_at = now() WHERE id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeRefreshToken(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeRefreshToken, id)
	return err
}
