// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: bookings.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countPendingOverlap = `-- name: CountPendingOverlap :one
SELECT count(*) FROM bookings
WHERE room_id = $1
  AND status = 'PENDING'
  AND id <> $2
  AND during && tstzrange($3::timestamptz, $4::timestamptz, '[)')
`

type CountPendingOverlapParams struct {
	RoomID    uuid.UUID          `json:"room_id"`
	ExcludeID uuid.UUID          `json:"exclude_id"`
	WinStart  pgtype.Timestamptz `json:"win_start"`
	WinEnd    pgtype.Timestamptz `json:"win_end"`
}

// Competing PENDING requests for the same room/window (FR8 surfacing).
func (q *Queries) CountPendingOverlap(ctx context.Context, arg CountPendingOverlapParams) (int64, error) {
	row := q.db.QueryRow(ctx, countPendingOverlap,
		arg.RoomID,
		arg.ExcludeID,
		arg.WinStart,
		arg.WinEnd,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createBooking = `-- name: CreateBooking :one

INSERT INTO bookings (room_id, requested_by, purpose, attendee_count, starts_at, ends_at, status)
VALUES ($1, $2, $3, $4, $5, $6, 'PENDING')
RETURNING id, room_id, requested_by, purpose, attendee_count, starts_at, ends_at, status,
          reviewed_by, review_note, reviewed_at, cancelled_at, created_at, updated_at
`

type CreateBookingParams struct {
	RoomID        uuid.UUID          `json:"room_id"`
	RequestedBy   uuid.UUID          `json:"requested_by"`
	Purpose       string             `json:"purpose"`
	AttendeeCount int32              `json:"attendee_count"`
	StartsAt      pgtype.Timestamptz `json:"starts_at"`
	EndsAt        pgtype.Timestamptz `json:"ends_at"`
}

type CreateBookingRow struct {
	ID            uuid.UUID          `json:"id"`
	RoomID        uuid.UUID          `json:"room_id"`
	RequestedBy   uuid.UUID          `json:"requested_by"`
	Purpose       string             `json:"purpose"`
	AttendeeCount int32              `json:"attendee_count"`
	StartsAt      pgtype.Timestamptz `json:"starts_at"`
	EndsAt        pgtype.Timestamptz `json:"ends_at"`
	Status        BookingStatus      `json:"status"`
	ReviewedBy    *uuid.UUID         `json:"reviewed_by"`
	ReviewNote    *string            `json:"review_note"`
	ReviewedAt    pgtype.Timestamptz `json:"reviewed_at"`
	CancelledAt   pgtype.Timestamptz `json:"cancelled_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

// Booking queries. We never SELECT the generated `during` column (a tstzrange);
// the partial EXCLUDE constraint and the validation trigger are the guarantees.
func (q *Queries) CreateBooking(ctx context.Context, arg CreateBookingParams) (CreateBookingRow, error) {
	row := q.db.QueryRow(ctx, createBooking,
		arg.RoomID,
		arg.RequestedBy,
		arg.Purpose,
		arg.AttendeeCount,
		arg.StartsAt,
		arg.EndsAt,
	)
	var i CreateBookingRow
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.RequestedBy,
		&i.Purpose,
		&i.AttendeeCount,
		&i.StartsAt,
		&i.EndsAt,
		&i.Status,
		&i.ReviewedBy,
		&i.ReviewNote,
		&i.ReviewedAt,
		&i.CancelledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const expireStalePending = `-- name: ExpireStalePending :execrows
UPDATE bookings SET status = 'EXPIRED', updated_at = now()
WHERE status = 'PENDING' AND starts_at < now()
`

// Set EXPIRED for PENDING bookings whose start time has passed (§7.2).
func (q *Queries) ExpireStalePending(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, expireStalePending)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getBooking = `-- name: GetBooking :one
SELECT id, room_id, requested_by, purpose, attendee_count, starts_at, ends_at, status,
       reviewed_by, review_note, reviewed_at, cancelled_at, created_at, updated_at
FROM bookings WHERE id = $1
`

type GetBookingRow struct {
	ID            uuid.UUID          `json:"id"`
	RoomID        uuid.UUID          `json:"room_id"`
	RequestedBy   uuid.UUID          `json:"requested_by"`
	Purpose       string             `json:"purpose"`
	AttendeeCount int32              `json:"attendee_count"`
	StartsAt      pgtype.Timestamptz `json:"starts_at"`
	EndsAt        pgtype.Timestamptz `json:"ends_at"`
	Status        BookingStatus      `json:"status"`
	ReviewedBy    *uuid.UUID         `json:"reviewed_by"`
	ReviewNote    *string            `json:"review_note"`
	ReviewedAt    pgtype.Timestamptz `json:"reviewed_at"`
	CancelledAt   pgtype.Timestamptz `json:"cancelled_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetBooking(ctx context.Context, id uuid.UUID) (GetBookingRow, error) {
	row := q.db.QueryRow(ctx, getBooking, id)
	var i GetBookingRow
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.RequestedBy,
		&i.Purpose,
		&i.AttendeeCount,
		&i.StartsAt,
		&i.EndsAt,
		&i.Status,
		&i.ReviewedBy,
		&i.ReviewNote,
		&i.ReviewedAt,
		&i.CancelledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBookingForUpdate = `-- name: GetBookingForUpdate :one
SELECT id, room_id, requested_by, purpose, attendee_count, starts_at, ends_at, status,
       reviewed_by, review_note, reviewed_at, cancelled_at, created_at, updated_at
FROM bookings WHERE id = $1 FOR UPDATE
`

type GetBookingForUpdateRow struct {
	ID            uuid.UUID          `json:"id"`
	RoomID        uuid.UUID          `json:"room_id"`
	RequestedBy   uuid.UUID          `json:"requested_by"`
	Purpose       string             `json:"purpose"`
	AttendeeCount int32              `json:"attendee_count"`
	StartsAt      pgtype.Timestamptz `json:"starts_at"`
	EndsAt        pgtype.Timestamptz `json:"ends_at"`
	Status        BookingStatus      `json:"status"`
	ReviewedBy    *uuid.UUID         `json:"reviewed_by"`
	ReviewNote    *string            `json:"review_note"`
	ReviewedAt    pgtype.Timestamptz `json:"reviewed_at"`
	CancelledAt   pgtype.Timestamptz `json:"cancelled_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

// Lock the row for the approval re-check (§7.3).
func (q *Queries) GetBookingForUpdate(ctx context.Context, id uuid.UUID) (GetBookingForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getBookingForUpdate, id)
	var i GetBookingForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.RequestedBy,
		&i.Purpose,
		&i.AttendeeCount,
		&i.StartsAt,
		&i.EndsAt,
		&i.Status,
		&i.ReviewedBy,
		&i.ReviewNote,
		&i.ReviewedAt,
		&i.CancelledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listApprovedBookingsForRoomInRange = `-- name: ListApprovedBookingsForRoomInRange :many
SELECT id, room_id, requested_by, purpose, attendee_count, starts_at, ends_at, status
FROM bookings
WHERE room_id = $1
  AND status = 'APPROVED'
  AND during && tstzrange($2::timestamptz, $3::timestamptz, '[)')
ORDER BY starts_at
`

type ListApprovedBookingsForRoomInRangeParams struct {
	RoomID   uuid.UUID          `json:"room_id"`
	DayStart pgtype.Timestamptz `json:"day_start"`
	DayEnd   pgtype.Timestamptz `json:"day_end"`
}

type ListApprovedBookingsForRoomInRangeRow struct {
	ID            uuid.UUID          `json:"id"`
	RoomID        uuid.UUID          `json:"room_id"`
	RequestedBy   uuid.UUID          `json:"requested_by"`
	Purpose       string             `json:"purpose"`
	AttendeeCount int32              `json:"attendee_count"`
	StartsAt      pgtype.Timestamptz `json:"starts_at"`
	EndsAt        pgtype.Timestamptz `json:"ends_at"`
	Status        BookingStatus      `json:"status"`
}

// Approved bookings whose time overlaps [day_start, day_end). Availability (§7.1, BR5).
func (q *Queries) ListApprovedBookingsForRoomInRange(ctx context.Context, arg ListApprovedBookingsForRoomInRangeParams) ([]ListApprovedBookingsForRoomInRangeRow, error) {
	rows, err := q.db.Query(ctx, listApprovedBookingsForRoomInRange, arg.RoomID, arg.DayStart, arg.DayEnd)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListApprovedBookingsForRoomInRangeRow
	for rows.Next() {
		var i ListApprovedBookingsForRoomInRangeRow
		if err := rows.Scan(
			&i.ID,
			&i.RoomID,
			&i.RequestedBy,
			&i.Purpose,
			&i.AttendeeCount,
			&i.StartsAt,
			&i.EndsAt,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBookings = `-- name: ListBookings :many
SELECT id, room_id, requested_by, purpose, attendee_count, starts_at, ends_at, status,
       reviewed_by, review_note, reviewed_at, cancelled_at, created_at, updated_at
FROM bookings
WHERE ($1::uuid IS NULL OR requested_by = $1)
  AND ($2::uuid IS NULL OR room_id = $2)
  AND ($3::booking_status IS NULL OR status = $3)
  AND ($4::timestamptz IS NULL OR starts_at >= $4)
  AND ($5::timestamptz IS NULL OR starts_at < $5)
  AND ($6::uuid IS NULL OR id < $6)
ORDER BY id DESC
LIMIT $7
`

type ListBookingsParams struct {
	RequesterID *uuid.UUID         `json:"requester_id"`
	RoomID      *uuid.UUID         `json:"room_id"`
	Status      *BookingStatus     `json:"status"`
	FromTs      pgtype.Timestamptz `json:"from_ts"`
	ToTs        pgtype.Timestamptz `json:"to_ts"`
	Cursor      *uuid.UUID         `json:"cursor"`
	Lim         int32              `json:"lim"`
}

type ListBookingsRow struct {
	ID            uuid.UUID          `json:"id"`
	RoomID        uuid.UUID          `json:"room_id"`
	RequestedBy   uuid.UUID          `json:"requested_by"`
	Purpose       string             `json:"purpose"`
	AttendeeCount int32              `json:"attendee_count"`
	StartsAt      pgtype.Timestamptz `json:"starts_at"`
	EndsAt        pgtype.Timestamptz `json:"ends_at"`
	Status        BookingStatus      `json:"status"`
	ReviewedBy    *uuid.UUID         `json:"reviewed_by"`
	ReviewNote    *string            `json:"review_note"`
	ReviewedAt    pgtype.Timestamptz `json:"reviewed_at"`
	CancelledAt   pgtype.Timestamptz `json:"cancelled_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListBookings(ctx context.Context, arg ListBookingsParams) ([]ListBookingsRow, error) {
	rows, err := q.db.Query(ctx, listBookings,
		arg.RequesterID,
		arg.RoomID,
		arg.Status,
		arg.FromTs,
		arg.ToTs,
		arg.Cursor,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBookingsRow
	for rows.Next() {
		var i ListBookingsRow
		if err := rows.Scan(
			&i.ID,
			&i.RoomID,
			&i.RequestedBy,
			&i.Purpose,
			&i.AttendeeCount,
			&i.StartsAt,
			&i.EndsAt,
			&i.Status,
			&i.ReviewedBy,
			&i.ReviewNote,
			&i.ReviewedAt,
			&i.CancelledAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listConflictingApprovedBookings = `-- name: ListConflictingApprovedBookings :many
SELECT id, room_id, requested_by, purpose, attendee_count, starts_at, ends_at, status
FROM bookings
WHERE room_id = $1
  AND status = 'APPROVED'
  AND id <> $2
  AND during && tstzrange($3::timestamptz, $4::timestamptz, '[)')
`

type ListConflictingApprovedBookingsParams struct {
	RoomID    uuid.UUID          `json:"room_id"`
	ExcludeID uuid.UUID          `json:"exclude_id"`
	WinStart  pgtype.Timestamptz `json:"win_start"`
	WinEnd    pgtype.Timestamptz `json:"win_end"`
}

type ListConflictingApprovedBookingsRow struct {
	ID            uuid.UUID          `json:"id"`
	RoomID        uuid.UUID          `json:"room_id"`
	RequestedBy   uuid.UUID          `json:"requested_by"`
	Purpose       string             `json:"purpose"`
	AttendeeCount int32              `json:"attendee_count"`
	StartsAt      pgtype.Timestamptz `json:"starts_at"`
	EndsAt        pgtype.Timestamptz `json:"ends_at"`
	Status        BookingStatus      `json:"status"`
}

// Other approved bookings overlapping the given window for a room (override support, BR6).
func (q *Queries) ListConflictingApprovedBookings(ctx context.Context, arg ListConflictingApprovedBookingsParams) ([]ListConflictingApprovedBookingsRow, error) {
	rows, err := q.db.Query(ctx, listConflictingApprovedBookings,
		arg.RoomID,
		arg.ExcludeID,
		arg.WinStart,
		arg.WinEnd,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListConflictingApprovedBookingsRow
	for rows.Next() {
		var i ListConflictingApprovedBookingsRow
		if err := rows.Scan(
			&i.ID,
			&i.RoomID,
			&i.RequestedBy,
			&i.Purpose,
			&i.AttendeeCount,
			&i.StartsAt,
			&i.EndsAt,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingForApproval = `-- name: ListPendingForApproval :many
SELECT b.id, b.room_id, b.requested_by, b.purpose, b.attendee_count,
       b.starts_at, b.ends_at, b.status, b.reviewed_by, b.review_note,
       b.reviewed_at, b.cancelled_at, b.created_at, b.updated_at,
       r.room_code        AS room_code,
       r.name             AS room_name,
       r.capacity         AS room_capacity,
       u.full_name        AS requester_full_name,
       u.department_id    AS requester_department_id,
       d.name             AS requester_department_name
FROM bookings b
JOIN rooms r ON r.id = b.room_id
JOIN users u ON u.id = b.requested_by
LEFT JOIN departments d ON d.id = u.department_id
WHERE b.status = 'PENDING'
  AND ($1::uuid IS NULL OR b.room_id = $1)
  AND ($2::uuid IS NULL OR b.id < $2)
ORDER BY b.id DESC
LIMIT $3
`

type ListPendingForApprovalParams struct {
	RoomID *uuid.UUID `json:"room_id"`
	Cursor *uuid.UUID `json:"cursor"`
	Lim    int32      `json:"lim"`
}

type ListPendingForApprovalRow struct {
	ID                      uuid.UUID          `json:"id"`
	RoomID                  uuid.UUID          `json:"room_id"`
	RequestedBy             uuid.UUID          `json:"requested_by"`
	Purpose                 string             `json:"purpose"`
	AttendeeCount           int32              `json:"attendee_count"`
	StartsAt                pgtype.Timestamptz `json:"starts_at"`
	EndsAt                  pgtype.Timestamptz `json:"ends_at"`
	Status                  BookingStatus      `json:"status"`
	ReviewedBy              *uuid.UUID         `json:"reviewed_by"`
	ReviewNote              *string            `json:"review_note"`
	ReviewedAt              pgtype.Timestamptz `json:"reviewed_at"`
	CancelledAt             pgtype.Timestamptz `json:"cancelled_at"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
	UpdatedAt               pgtype.Timestamptz `json:"updated_at"`
	RoomCode                string             `json:"room_code"`
	RoomName                string             `json:"room_name"`
	RoomCapacity            int32              `json:"room_capacity"`
	RequesterFullName       string             `json:"requester_full_name"`
	RequesterDepartmentID   *uuid.UUID         `json:"requester_department_id"`
	RequesterDepartmentName *string            `json:"requester_department_name"`
}

// Pending bookings enriched with room + requester (+ department) for the
// approvals queue (FR8, §11). Joined here so the handler avoids N+1 lookups; the
// approvability blockers are then computed per row in the service layer.
func (q *Queries) ListPendingForApproval(ctx context.Context, arg ListPendingForApprovalParams) ([]ListPendingForApprovalRow, error) {
	rows, err := q.db.Query(ctx, listPendingForApproval, arg.RoomID, arg.Cursor, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPendingForApprovalRow
	for rows.Next() {
		var i ListPendingForApprovalRow
		if err := rows.Scan(
			&i.ID,
			&i.RoomID,
			&i.RequestedBy,
			&i.Purpose,
			&i.AttendeeCount,
			&i.StartsAt,
			&i.EndsAt,
			&i.Status,
			&i.ReviewedBy,
			&i.ReviewNote,
			&i.ReviewedAt,
			&i.CancelledAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RoomCode,
			&i.RoomName,
			&i.RoomCapacity,
			&i.RequesterFullName,
			&i.RequesterDepartmentID,
			&i.RequesterDepartmentName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setBookingStatus = `-- name: SetBookingStatus :one
UPDATE bookings
SET status = $2,
    reviewed_by = COALESCE($3, reviewed_by),
    review_note = COALESCE($4, review_note),
    reviewed_at = CASE WHEN $2 IN ('APPROVED'::booking_status,'REJECTED'::booking_status) THEN now() ELSE reviewed_at END,
    cancelled_at = CASE WHEN $2 = 'CANCELLED'::booking_status THEN now() ELSE cancelled_at END,
    updated_at = now()
WHERE id = $1
RETURNING id, room_id, requested_by, purpose, attendee_count, starts_at, ends_at, status,
          reviewed_by, review_note, reviewed_at, cancelled_at, created_at, updated_at
`

type SetBookingStatusParams struct {
	ID         uuid.UUID     `json:"id"`
	Status     BookingStatus `json:"status"`
	ReviewedBy *uuid.UUID    `json:"reviewed_by"`
	ReviewNote *string       `json:"review_note"`
}

type SetBookingStatusRow struct {
	ID            uuid.UUID          `json:"id"`
	RoomID        uuid.UUID          `json:"room_id"`
	RequestedBy   uuid.UUID          `json:"requested_by"`
	Purpose       string             `json:"purpose"`
	AttendeeCount int32              `json:"attendee_count"`
	StartsAt      pgtype.Timestamptz `json:"starts_at"`
	EndsAt        pgtype.Timestamptz `json:"ends_at"`
	Status        BookingStatus      `json:"status"`
	ReviewedBy    *uuid.UUID         `json:"reviewed_by"`
	ReviewNote    *string            `json:"review_note"`
	ReviewedAt    pgtype.Timestamptz `json:"reviewed_at"`
	CancelledAt   pgtype.Timestamptz `json:"cancelled_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

// Generic status transition used by approve/reject/cancel/override/expire.
func (q *Queries) SetBookingStatus(ctx context.Context, arg SetBookingStatusParams) (SetBookingStatusRow, error) {
	row := q.db.QueryRow(ctx, setBookingStatus,
		arg.ID,
		arg.Status,
		arg.ReviewedBy,
		arg.ReviewNote,
	)
	var i SetBookingStatusRow
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.RequestedBy,
		&i.Purpose,
		&i.AttendeeCount,
		&i.StartsAt,
		&i.EndsAt,
		&i.Status,
		&i.ReviewedBy,
		&i.ReviewNote,
		&i.ReviewedAt,
		&i.CancelledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
