// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: catalogue.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
)

const addRoomEquipment = `-- name: AddRoomEquipment :exec
INSERT INTO room_equipment (room_id, equipment_id, quantity)
VALUES ($1, $2, $3)
ON CONFLICT (room_id, equipment_id) DO UPDATE SET quantity = EXCLUDED.quantity
`

type AddRoomEquipmentParams struct {
	RoomID      uuid.UUID `json:"room_id"`
	EquipmentID uuid.UUID `json:"equipment_id"`
	Quantity    int32     `json:"quantity"`
}

func (q *Queries) AddRoomEquipment(ctx context.Context, arg AddRoomEquipmentParams) error {
	_, err := q.db.Exec(ctx, addRoomEquipment, arg.RoomID, arg.EquipmentID, arg.Quantity)
	return err
}

const clearRoomEquipment = `-- name: ClearRoomEquipment :exec
DELETE FROM room_equipment WHERE room_id = $1
`

func (q *Queries) ClearRoomEquipment(ctx context.Context, roomID uuid.UUID) error {
	_, err := q.db.Exec(ctx, clearRoomEquipment, roomID)
	return err
}

const createBuilding = `-- name: CreateBuilding :one
INSERT INTO buildings (code, name, campus) VALUES ($1, $2, $3) RETURNING id, code, name, campus, created_at, updated_at, image_url, image_public_id, gallery_urls, gallery_public_ids
`

type CreateBuildingParams struct {
	Code   string  `json:"code"`
	Name   string  `json:"name"`
	Campus *string `json:"campus"`
}

// ── Buildings ─────────────────────────────────────────────────
func (q *Queries) CreateBuilding(ctx context.Context, arg CreateBuildingParams) (Building, error) {
	row := q.db.QueryRow(ctx, createBuilding, arg.Code, arg.Name, arg.Campus)
	var i Building
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Campus,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ImageUrl,
		&i.ImagePublicID,
		&i.GalleryUrls,
		&i.GalleryPublicIds,
	)
	return i, err
}

const createEquipment = `-- name: CreateEquipment :one
INSERT INTO equipment (code, name) VALUES ($1, $2) RETURNING id, code, name, image_url, image_public_id, gallery_urls, gallery_public_ids
`

type CreateEquipmentParams struct {
	Code string `json:"code"`
	Name string `json:"name"`
}

// ── Equipment ─────────────────────────────────────────────────
func (q *Queries) CreateEquipment(ctx context.Context, arg CreateEquipmentParams) (Equipment, error) {
	row := q.db.QueryRow(ctx, createEquipment, arg.Code, arg.Name)
	var i Equipment
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.ImageUrl,
		&i.ImagePublicID,
		&i.GalleryUrls,
		&i.GalleryPublicIds,
	)
	return i, err
}

const createRoom = `-- name: CreateRoom :one
INSERT INTO rooms (room_code, name, building_id, capacity, room_type, status)
VALUES ($1, $2, $3, $4, $5, $6) RETURNING id, room_code, name, building_id, capacity, room_type, status, created_at, updated_at, image_url, image_public_id, gallery_urls, gallery_public_ids
`

type CreateRoomParams struct {
	RoomCode   string     `json:"room_code"`
	Name       string     `json:"name"`
	BuildingID uuid.UUID  `json:"building_id"`
	Capacity   int32      `json:"capacity"`
	RoomType   RoomType   `json:"room_type"`
	Status     RoomStatus `json:"status"`
}

// ── Rooms ─────────────────────────────────────────────────────
func (q *Queries) CreateRoom(ctx context.Context, arg CreateRoomParams) (Room, error) {
	row := q.db.QueryRow(ctx, createRoom,
		arg.RoomCode,
		arg.Name,
		arg.BuildingID,
		arg.Capacity,
		arg.RoomType,
		arg.Status,
	)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.RoomCode,
		&i.Name,
		&i.BuildingID,
		&i.Capacity,
		&i.RoomType,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ImageUrl,
		&i.ImagePublicID,
		&i.GalleryUrls,
		&i.GalleryPublicIds,
	)
	return i, err
}

const deleteBuilding = `-- name: DeleteBuilding :exec
DELETE FROM buildings WHERE id = $1
`

func (q *Queries) DeleteBuilding(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteBuilding, id)
	return err
}

const deleteEquipment = `-- name: DeleteEquipment :exec
DELETE FROM equipment WHERE id = $1
`

func (q *Queries) DeleteEquipment(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteEquipment, id)
	return err
}

const getBuilding = `-- name: GetBuilding :one
SELECT id, code, name, campus, created_at, updated_at, image_url, image_public_id, gallery_urls, gallery_public_ids FROM buildings WHERE id = $1
`

func (q *Queries) GetBuilding(ctx context.Context, id uuid.UUID) (Building, error) {
	row := q.db.QueryRow(ctx, getBuilding, id)
	var i Building
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Campus,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ImageUrl,
		&i.ImagePublicID,
		&i.GalleryUrls,
		&i.GalleryPublicIds,
	)
	return i, err
}

const getBuildingByName = `-- name: GetBuildingByName :one
SELECT id, code, name, campus, created_at, updated_at, image_url, image_public_id, gallery_urls, gallery_public_ids FROM buildings WHERE lower(name) = lower($1)
`

func (q *Queries) GetBuildingByName(ctx context.Context, lower string) (Building, error) {
	row := q.db.QueryRow(ctx, getBuildingByName, lower)
	var i Building
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Campus,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ImageUrl,
		&i.ImagePublicID,
		&i.GalleryUrls,
		&i.GalleryPublicIds,
	)
	return i, err
}

const getEquipment = `-- name: GetEquipment :one
SELECT id, code, name, image_url, image_public_id, gallery_urls, gallery_public_ids FROM equipment WHERE id = $1
`

func (q *Queries) GetEquipment(ctx context.Context, id uuid.UUID) (Equipment, error) {
	row := q.db.QueryRow(ctx, getEquipment, id)
	var i Equipment
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.ImageUrl,
		&i.ImagePublicID,
		&i.GalleryUrls,
		&i.GalleryPublicIds,
	)
	return i, err
}

const getRoom = `-- name: GetRoom :one
SELECT id, room_code, name, building_id, capacity, room_type, status, created_at, updated_at, image_url, image_public_id, gallery_urls, gallery_public_ids FROM rooms WHERE id = $1
`

func (q *Queries) GetRoom(ctx context.Context, id uuid.UUID) (Room, error) {
	row := q.db.QueryRow(ctx, getRoom, id)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.RoomCode,
		&i.Name,
		&i.BuildingID,
		&i.Capacity,
		&i.RoomType,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ImageUrl,
		&i.ImagePublicID,
		&i.GalleryUrls,
		&i.GalleryPublicIds,
	)
	return i, err
}

const getRoomByCode = `-- name: GetRoomByCode :one
SELECT id, room_code, name, building_id, capacity, room_type, status, created_at, updated_at, image_url, image_public_id, gallery_urls, gallery_public_ids FROM rooms WHERE room_code = $1
`

func (q *Queries) GetRoomByCode(ctx context.Context, roomCode string) (Room, error) {
	row := q.db.QueryRow(ctx, getRoomByCode, roomCode)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.RoomCode,
		&i.Name,
		&i.BuildingID,
		&i.Capacity,
		&i.RoomType,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ImageUrl,
		&i.ImagePublicID,
		&i.GalleryUrls,
		&i.GalleryPublicIds,
	)
	return i, err
}

const getRoomByName = `-- name: GetRoomByName :one
SELECT id, room_code, name, building_id, capacity, room_type, status, created_at, updated_at, image_url, image_public_id, gallery_urls, gallery_public_ids FROM rooms WHERE lower(name) = lower($1)
`

func (q *Queries) GetRoomByName(ctx context.Context, lower string) (Room, error) {
	row := q.db.QueryRow(ctx, getRoomByName, lower)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.RoomCode,
		&i.Name,
		&i.BuildingID,
		&i.Capacity,
		&i.RoomType,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ImageUrl,
		&i.ImagePublicID,
		&i.GalleryUrls,
		&i.GalleryPublicIds,
	)
	return i, err
}

const listBuildings = `-- name: ListBuildings :many
SELECT id, code, name, campus, created_at, updated_at, image_url, image_public_id, gallery_urls, gallery_public_ids FROM buildings ORDER BY code
`

func (q *Queries) ListBuildings(ctx context.Context) ([]Building, error) {
	rows, err := q.db.Query(ctx, listBuildings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Building
	for rows.Next() {
		var i Building
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.Campus,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ImageUrl,
			&i.ImagePublicID,
			&i.GalleryUrls,
			&i.GalleryPublicIds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEquipment = `-- name: ListEquipment :many
SELECT id, code, name, image_url, image_public_id, gallery_urls, gallery_public_ids FROM equipment ORDER BY code
`

func (q *Queries) ListEquipment(ctx context.Context) ([]Equipment, error) {
	rows, err := q.db.Query(ctx, listEquipment)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Equipment
	for rows.Next() {
		var i Equipment
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.ImageUrl,
			&i.ImagePublicID,
			&i.GalleryUrls,
			&i.GalleryPublicIds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoomEquipment = `-- name: ListRoomEquipment :many
SELECT re.equipment_id, e.code, e.name, e.image_url, re.quantity
FROM room_equipment re JOIN equipment e ON e.id = re.equipment_id
WHERE re.room_id = $1
ORDER BY e.code
`

type ListRoomEquipmentRow struct {
	EquipmentID uuid.UUID `json:"equipment_id"`
	Code        string    `json:"code"`
	Name        string    `json:"name"`
	ImageUrl    *string   `json:"image_url"`
	Quantity    int32     `json:"quantity"`
}

func (q *Queries) ListRoomEquipment(ctx context.Context, roomID uuid.UUID) ([]ListRoomEquipmentRow, error) {
	rows, err := q.db.Query(ctx, listRoomEquipment, roomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRoomEquipmentRow
	for rows.Next() {
		var i ListRoomEquipmentRow
		if err := rows.Scan(
			&i.EquipmentID,
			&i.Code,
			&i.Name,
			&i.ImageUrl,
			&i.Quantity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setRoomStatus = `-- name: SetRoomStatus :one
UPDATE rooms SET status = $2, updated_at = now() WHERE id = $1 RETURNING id, room_code, name, building_id, capacity, room_type, status, created_at, updated_at, image_url, image_public_id, gallery_urls, gallery_public_ids
`

type SetRoomStatusParams struct {
	ID     uuid.UUID  `json:"id"`
	Status RoomStatus `json:"status"`
}

func (q *Queries) SetRoomStatus(ctx context.Context, arg SetRoomStatusParams) (Room, error) {
	row := q.db.QueryRow(ctx, setRoomStatus, arg.ID, arg.Status)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.RoomCode,
		&i.Name,
		&i.BuildingID,
		&i.Capacity,
		&i.RoomType,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ImageUrl,
		&i.ImagePublicID,
		&i.GalleryUrls,
		&i.GalleryPublicIds,
	)
	return i, err
}

const updateBuilding = `-- name: UpdateBuilding :one
UPDATE buildings SET code = $2, name = $3, campus = $4, updated_at = now()
WHERE id = $1 RETURNING id, code, name, campus, created_at, updated_at, image_url, image_public_id, gallery_urls, gallery_public_ids
`

type UpdateBuildingParams struct {
	ID     uuid.UUID `json:"id"`
	Code   string    `json:"code"`
	Name   string    `json:"name"`
	Campus *string   `json:"campus"`
}

func (q *Queries) UpdateBuilding(ctx context.Context, arg UpdateBuildingParams) (Building, error) {
	row := q.db.QueryRow(ctx, updateBuilding,
		arg.ID,
		arg.Code,
		arg.Name,
		arg.Campus,
	)
	var i Building
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Campus,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ImageUrl,
		&i.ImagePublicID,
		&i.GalleryUrls,
		&i.GalleryPublicIds,
	)
	return i, err
}

const updateBuildingImages = `-- name: UpdateBuildingImages :one
UPDATE buildings
SET image_url = $2,
    image_public_id = $3,
    gallery_urls = $4,
    gallery_public_ids = $5,
    updated_at = now()
WHERE id = $1 RETURNING id, code, name, campus, created_at, updated_at, image_url, image_public_id, gallery_urls, gallery_public_ids
`

type UpdateBuildingImagesParams struct {
	ID               uuid.UUID `json:"id"`
	ImageUrl         *string   `json:"image_url"`
	ImagePublicID    *string   `json:"image_public_id"`
	GalleryUrls      []string  `json:"gallery_urls"`
	GalleryPublicIds []string  `json:"gallery_public_ids"`
}

func (q *Queries) UpdateBuildingImages(ctx context.Context, arg UpdateBuildingImagesParams) (Building, error) {
	row := q.db.QueryRow(ctx, updateBuildingImages,
		arg.ID,
		arg.ImageUrl,
		arg.ImagePublicID,
		arg.GalleryUrls,
		arg.GalleryPublicIds,
	)
	var i Building
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Campus,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ImageUrl,
		&i.ImagePublicID,
		&i.GalleryUrls,
		&i.GalleryPublicIds,
	)
	return i, err
}

const updateEquipment = `-- name: UpdateEquipment :one
UPDATE equipment SET code = $2, name = $3 WHERE id = $1 RETURNING id, code, name, image_url, image_public_id, gallery_urls, gallery_public_ids
`

type UpdateEquipmentParams struct {
	ID   uuid.UUID `json:"id"`
	Code string    `json:"code"`
	Name string    `json:"name"`
}

func (q *Queries) UpdateEquipment(ctx context.Context, arg UpdateEquipmentParams) (Equipment, error) {
	row := q.db.QueryRow(ctx, updateEquipment, arg.ID, arg.Code, arg.Name)
	var i Equipment
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.ImageUrl,
		&i.ImagePublicID,
		&i.GalleryUrls,
		&i.GalleryPublicIds,
	)
	return i, err
}

const updateEquipmentImages = `-- name: UpdateEquipmentImages :one
UPDATE equipment
SET image_url = $2,
    image_public_id = $3,
    gallery_urls = $4,
    gallery_public_ids = $5
WHERE id = $1 RETURNING id, code, name, image_url, image_public_id, gallery_urls, gallery_public_ids
`

type UpdateEquipmentImagesParams struct {
	ID               uuid.UUID `json:"id"`
	ImageUrl         *string   `json:"image_url"`
	ImagePublicID    *string   `json:"image_public_id"`
	GalleryUrls      []string  `json:"gallery_urls"`
	GalleryPublicIds []string  `json:"gallery_public_ids"`
}

func (q *Queries) UpdateEquipmentImages(ctx context.Context, arg UpdateEquipmentImagesParams) (Equipment, error) {
	row := q.db.QueryRow(ctx, updateEquipmentImages,
		arg.ID,
		arg.ImageUrl,
		arg.ImagePublicID,
		arg.GalleryUrls,
		arg.GalleryPublicIds,
	)
	var i Equipment
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.ImageUrl,
		&i.ImagePublicID,
		&i.GalleryUrls,
		&i.GalleryPublicIds,
	)
	return i, err
}

const updateRoom = `-- name: UpdateRoom :one
UPDATE rooms SET room_code = $2, name = $3, building_id = $4, capacity = $5,
                 room_type = $6, status = $7, updated_at = now()
WHERE id = $1 RETURNING id, room_code, name, building_id, capacity, room_type, status, created_at, updated_at, image_url, image_public_id, gallery_urls, gallery_public_ids
`

type UpdateRoomParams struct {
	ID         uuid.UUID  `json:"id"`
	RoomCode   string     `json:"room_code"`
	Name       string     `json:"name"`
	BuildingID uuid.UUID  `json:"building_id"`
	Capacity   int32      `json:"capacity"`
	RoomType   RoomType   `json:"room_type"`
	Status     RoomStatus `json:"status"`
}

func (q *Queries) UpdateRoom(ctx context.Context, arg UpdateRoomParams) (Room, error) {
	row := q.db.QueryRow(ctx, updateRoom,
		arg.ID,
		arg.RoomCode,
		arg.Name,
		arg.BuildingID,
		arg.Capacity,
		arg.RoomType,
		arg.Status,
	)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.RoomCode,
		&i.Name,
		&i.BuildingID,
		&i.Capacity,
		&i.RoomType,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ImageUrl,
		&i.ImagePublicID,
		&i.GalleryUrls,
		&i.GalleryPublicIds,
	)
	return i, err
}

const updateRoomImages = `-- name: UpdateRoomImages :one
UPDATE rooms
SET image_url = $2,
    image_public_id = $3,
    gallery_urls = $4,
    gallery_public_ids = $5,
    updated_at = now()
WHERE id = $1 RETURNING id, room_code, name, building_id, capacity, room_type, status, created_at, updated_at, image_url, image_public_id, gallery_urls, gallery_public_ids
`

type UpdateRoomImagesParams struct {
	ID               uuid.UUID `json:"id"`
	ImageUrl         *string   `json:"image_url"`
	ImagePublicID    *string   `json:"image_public_id"`
	GalleryUrls      []string  `json:"gallery_urls"`
	GalleryPublicIds []string  `json:"gallery_public_ids"`
}

func (q *Queries) UpdateRoomImages(ctx context.Context, arg UpdateRoomImagesParams) (Room, error) {
	row := q.db.QueryRow(ctx, updateRoomImages,
		arg.ID,
		arg.ImageUrl,
		arg.ImagePublicID,
		arg.GalleryUrls,
		arg.GalleryPublicIds,
	)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.RoomCode,
		&i.Name,
		&i.BuildingID,
		&i.Capacity,
		&i.RoomType,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ImageUrl,
		&i.ImagePublicID,
		&i.GalleryUrls,
		&i.GalleryPublicIds,
	)
	return i, err
}
