// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: identity.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createDepartment = `-- name: CreateDepartment :one
INSERT INTO departments (code, name, faculty)
VALUES ($1, $2, $3)
RETURNING id, code, name, faculty, created_at, updated_at
`

type CreateDepartmentParams struct {
	Code    string  `json:"code"`
	Name    string  `json:"name"`
	Faculty *string `json:"faculty"`
}

// ── Departments ───────────────────────────────────────────────
func (q *Queries) CreateDepartment(ctx context.Context, arg CreateDepartmentParams) (Department, error) {
	row := q.db.QueryRow(ctx, createDepartment, arg.Code, arg.Name, arg.Faculty)
	var i Department
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Faculty,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, password_hash, full_name, role, department_id, status)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, email, password_hash, full_name, role, department_id, status, mfa_enabled, mfa_secret_encrypted, failed_login_attempts, locked_until, last_login_at, created_at, updated_at
`

type CreateUserParams struct {
	Email        string     `json:"email"`
	PasswordHash string     `json:"password_hash"`
	FullName     string     `json:"full_name"`
	Role         UserRole   `json:"role"`
	DepartmentID *uuid.UUID `json:"department_id"`
	Status       UserStatus `json:"status"`
}

// ── Users ─────────────────────────────────────────────────────
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.PasswordHash,
		arg.FullName,
		arg.Role,
		arg.DepartmentID,
		arg.Status,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.FullName,
		&i.Role,
		&i.DepartmentID,
		&i.Status,
		&i.MfaEnabled,
		&i.MfaSecretEncrypted,
		&i.FailedLoginAttempts,
		&i.LockedUntil,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteDepartment = `-- name: DeleteDepartment :exec
DELETE FROM departments WHERE id = $1
`

func (q *Queries) DeleteDepartment(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteDepartment, id)
	return err
}

const enableMFA = `-- name: EnableMFA :exec
UPDATE users SET mfa_enabled = true, updated_at = now() WHERE id = $1
`

func (q *Queries) EnableMFA(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, enableMFA, id)
	return err
}

const getDepartment = `-- name: GetDepartment :one
SELECT id, code, name, faculty, created_at, updated_at FROM departments WHERE id = $1
`

func (q *Queries) GetDepartment(ctx context.Context, id uuid.UUID) (Department, error) {
	row := q.db.QueryRow(ctx, getDepartment, id)
	var i Department
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Faculty,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, full_name, role, department_id, status, mfa_enabled, mfa_secret_encrypted, failed_login_attempts, locked_until, last_login_at, created_at, updated_at FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.FullName,
		&i.Role,
		&i.DepartmentID,
		&i.Status,
		&i.MfaEnabled,
		&i.MfaSecretEncrypted,
		&i.FailedLoginAttempts,
		&i.LockedUntil,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, password_hash, full_name, role, department_id, status, mfa_enabled, mfa_secret_encrypted, failed_login_attempts, locked_until, last_login_at, created_at, updated_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.FullName,
		&i.Role,
		&i.DepartmentID,
		&i.Status,
		&i.MfaEnabled,
		&i.MfaSecretEncrypted,
		&i.FailedLoginAttempts,
		&i.LockedUntil,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDepartments = `-- name: ListDepartments :many
SELECT id, code, name, faculty, created_at, updated_at FROM departments ORDER BY code
`

func (q *Queries) ListDepartments(ctx context.Context) ([]Department, error) {
	rows, err := q.db.Query(ctx, listDepartments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Department
	for rows.Next() {
		var i Department
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.Faculty,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT id, email, password_hash, full_name, role, department_id, status, mfa_enabled, mfa_secret_encrypted, failed_login_attempts, locked_until, last_login_at, created_at, updated_at FROM users
WHERE ($1::user_role IS NULL OR role = $1)
  AND ($2::uuid IS NULL OR department_id = $2)
  AND ($3::user_status IS NULL OR status = $3)
  AND ($4::uuid IS NULL OR id > $4)
ORDER BY id
LIMIT $5
`

type ListUsersParams struct {
	Role         *UserRole   `json:"role"`
	DepartmentID *uuid.UUID  `json:"department_id"`
	Status       *UserStatus `json:"status"`
	Cursor       *uuid.UUID  `json:"cursor"`
	Lim          int32       `json:"lim"`
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers,
		arg.Role,
		arg.DepartmentID,
		arg.Status,
		arg.Cursor,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.PasswordHash,
			&i.FullName,
			&i.Role,
			&i.DepartmentID,
			&i.Status,
			&i.MfaEnabled,
			&i.MfaSecretEncrypted,
			&i.FailedLoginAttempts,
			&i.LockedUntil,
			&i.LastLoginAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordFailedLogin = `-- name: RecordFailedLogin :one
UPDATE users
SET failed_login_attempts = failed_login_attempts + 1,
    locked_until = CASE WHEN failed_login_attempts + 1 >= $2
                        THEN now() + $3::interval ELSE locked_until END,
    updated_at = now()
WHERE id = $1
RETURNING failed_login_attempts, locked_until
`

type RecordFailedLoginParams struct {
	ID          uuid.UUID       `json:"id"`
	MaxAttempts int32           `json:"max_attempts"`
	LockWindow  pgtype.Interval `json:"lock_window"`
}

type RecordFailedLoginRow struct {
	FailedLoginAttempts int32              `json:"failed_login_attempts"`
	LockedUntil         pgtype.Timestamptz `json:"locked_until"`
}

func (q *Queries) RecordFailedLogin(ctx context.Context, arg RecordFailedLoginParams) (RecordFailedLoginRow, error) {
	row := q.db.QueryRow(ctx, recordFailedLogin, arg.ID, arg.MaxAttempts, arg.LockWindow)
	var i RecordFailedLoginRow
	err := row.Scan(&i.FailedLoginAttempts, &i.LockedUntil)
	return i, err
}

const recordSuccessfulLogin = `-- name: RecordSuccessfulLogin :exec
UPDATE users
SET last_login_at = now(), failed_login_attempts = 0, locked_until = NULL, updated_at = now()
WHERE id = $1
`

func (q *Queries) RecordSuccessfulLogin(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, recordSuccessfulLogin, id)
	return err
}

const setMFASecret = `-- name: SetMFASecret :exec
UPDATE users SET mfa_secret_encrypted = $2, updated_at = now() WHERE id = $1
`

type SetMFASecretParams struct {
	ID                 uuid.UUID `json:"id"`
	MfaSecretEncrypted []byte    `json:"mfa_secret_encrypted"`
}

func (q *Queries) SetMFASecret(ctx context.Context, arg SetMFASecretParams) error {
	_, err := q.db.Exec(ctx, setMFASecret, arg.ID, arg.MfaSecretEncrypted)
	return err
}

const setUserStatus = `-- name: SetUserStatus :one
UPDATE users SET status = $2, updated_at = now() WHERE id = $1 RETURNING id, email, password_hash, full_name, role, department_id, status, mfa_enabled, mfa_secret_encrypted, failed_login_attempts, locked_until, last_login_at, created_at, updated_at
`

type SetUserStatusParams struct {
	ID     uuid.UUID  `json:"id"`
	Status UserStatus `json:"status"`
}

func (q *Queries) SetUserStatus(ctx context.Context, arg SetUserStatusParams) (User, error) {
	row := q.db.QueryRow(ctx, setUserStatus, arg.ID, arg.Status)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.FullName,
		&i.Role,
		&i.DepartmentID,
		&i.Status,
		&i.MfaEnabled,
		&i.MfaSecretEncrypted,
		&i.FailedLoginAttempts,
		&i.LockedUntil,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateDepartment = `-- name: UpdateDepartment :one
UPDATE departments SET code = $2, name = $3, faculty = $4, updated_at = now()
WHERE id = $1 RETURNING id, code, name, faculty, created_at, updated_at
`

type UpdateDepartmentParams struct {
	ID      uuid.UUID `json:"id"`
	Code    string    `json:"code"`
	Name    string    `json:"name"`
	Faculty *string   `json:"faculty"`
}

func (q *Queries) UpdateDepartment(ctx context.Context, arg UpdateDepartmentParams) (Department, error) {
	row := q.db.QueryRow(ctx, updateDepartment,
		arg.ID,
		arg.Code,
		arg.Name,
		arg.Faculty,
	)
	var i Department
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Faculty,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePasswordHash = `-- name: UpdatePasswordHash :exec
UPDATE users SET password_hash = $2, updated_at = now() WHERE id = $1
`

type UpdatePasswordHashParams struct {
	ID           uuid.UUID `json:"id"`
	PasswordHash string    `json:"password_hash"`
}

func (q *Queries) UpdatePasswordHash(ctx context.Context, arg UpdatePasswordHashParams) error {
	_, err := q.db.Exec(ctx, updatePasswordHash, arg.ID, arg.PasswordHash)
	return err
}

const updateUserProfile = `-- name: UpdateUserProfile :one
UPDATE users SET full_name = $2, department_id = $3, updated_at = now()
WHERE id = $1 RETURNING id, email, password_hash, full_name, role, department_id, status, mfa_enabled, mfa_secret_encrypted, failed_login_attempts, locked_until, last_login_at, created_at, updated_at
`

type UpdateUserProfileParams struct {
	ID           uuid.UUID  `json:"id"`
	FullName     string     `json:"full_name"`
	DepartmentID *uuid.UUID `json:"department_id"`
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserProfile, arg.ID, arg.FullName, arg.DepartmentID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.FullName,
		&i.Role,
		&i.DepartmentID,
		&i.Status,
		&i.MfaEnabled,
		&i.MfaSecretEncrypted,
		&i.FailedLoginAttempts,
		&i.LockedUntil,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserRole = `-- name: UpdateUserRole :one
UPDATE users SET role = $2, updated_at = now() WHERE id = $1 RETURNING id, email, password_hash, full_name, role, department_id, status, mfa_enabled, mfa_secret_encrypted, failed_login_attempts, locked_until, last_login_at, created_at, updated_at
`

type UpdateUserRoleParams struct {
	ID   uuid.UUID `json:"id"`
	Role UserRole  `json:"role"`
}

func (q *Queries) UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserRole, arg.ID, arg.Role)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.FullName,
		&i.Role,
		&i.DepartmentID,
		&i.Status,
		&i.MfaEnabled,
		&i.MfaSecretEncrypted,
		&i.FailedLoginAttempts,
		&i.LockedUntil,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
