// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"database/sql/driver"
	"fmt"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type BookingStatus string

const (
	BookingStatusPENDING   BookingStatus = "PENDING"
	BookingStatusAPPROVED  BookingStatus = "APPROVED"
	BookingStatusREJECTED  BookingStatus = "REJECTED"
	BookingStatusCANCELLED BookingStatus = "CANCELLED"
	BookingStatusEXPIRED   BookingStatus = "EXPIRED"
)

func (e *BookingStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = BookingStatus(s)
	case string:
		*e = BookingStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for BookingStatus: %T", src)
	}
	return nil
}

type NullBookingStatus struct {
	BookingStatus BookingStatus `json:"booking_status"`
	Valid         bool          `json:"valid"` // Valid is true if BookingStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullBookingStatus) Scan(value interface{}) error {
	if value == nil {
		ns.BookingStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.BookingStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullBookingStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.BookingStatus), nil
}

type DayOfWeek string

const (
	DayOfWeekMON DayOfWeek = "MON"
	DayOfWeekTUE DayOfWeek = "TUE"
	DayOfWeekWED DayOfWeek = "WED"
	DayOfWeekTHU DayOfWeek = "THU"
	DayOfWeekFRI DayOfWeek = "FRI"
	DayOfWeekSAT DayOfWeek = "SAT"
	DayOfWeekSUN DayOfWeek = "SUN"
)

func (e *DayOfWeek) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DayOfWeek(s)
	case string:
		*e = DayOfWeek(s)
	default:
		return fmt.Errorf("unsupported scan type for DayOfWeek: %T", src)
	}
	return nil
}

type NullDayOfWeek struct {
	DayOfWeek DayOfWeek `json:"day_of_week"`
	Valid     bool      `json:"valid"` // Valid is true if DayOfWeek is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDayOfWeek) Scan(value interface{}) error {
	if value == nil {
		ns.DayOfWeek, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DayOfWeek.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDayOfWeek) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DayOfWeek), nil
}

type ImportMethod string

const (
	ImportMethodEXCEL  ImportMethod = "EXCEL"
	ImportMethodCSV    ImportMethod = "CSV"
	ImportMethodMANUAL ImportMethod = "MANUAL"
)

func (e *ImportMethod) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ImportMethod(s)
	case string:
		*e = ImportMethod(s)
	default:
		return fmt.Errorf("unsupported scan type for ImportMethod: %T", src)
	}
	return nil
}

type NullImportMethod struct {
	ImportMethod ImportMethod `json:"import_method"`
	Valid        bool         `json:"valid"` // Valid is true if ImportMethod is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullImportMethod) Scan(value interface{}) error {
	if value == nil {
		ns.ImportMethod, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ImportMethod.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullImportMethod) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ImportMethod), nil
}

type ImportStatus string

const (
	ImportStatusPENDING            ImportStatus = "PENDING"
	ImportStatusPROCESSING         ImportStatus = "PROCESSING"
	ImportStatusCOMPLETED          ImportStatus = "COMPLETED"
	ImportStatusFAILED             ImportStatus = "FAILED"
	ImportStatusPARTIALLYCOMPLETED ImportStatus = "PARTIALLY_COMPLETED"
)

func (e *ImportStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ImportStatus(s)
	case string:
		*e = ImportStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ImportStatus: %T", src)
	}
	return nil
}

type NullImportStatus struct {
	ImportStatus ImportStatus `json:"import_status"`
	Valid        bool         `json:"valid"` // Valid is true if ImportStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullImportStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ImportStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ImportStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullImportStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ImportStatus), nil
}

type NotifChannel string

const (
	NotifChannelEMAIL NotifChannel = "EMAIL"
	NotifChannelINAPP NotifChannel = "IN_APP"
	NotifChannelPUSH  NotifChannel = "PUSH"
)

func (e *NotifChannel) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = NotifChannel(s)
	case string:
		*e = NotifChannel(s)
	default:
		return fmt.Errorf("unsupported scan type for NotifChannel: %T", src)
	}
	return nil
}

type NullNotifChannel struct {
	NotifChannel NotifChannel `json:"notif_channel"`
	Valid        bool         `json:"valid"` // Valid is true if NotifChannel is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullNotifChannel) Scan(value interface{}) error {
	if value == nil {
		ns.NotifChannel, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.NotifChannel.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullNotifChannel) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.NotifChannel), nil
}

type RoomStatus string

const (
	RoomStatusACTIVE           RoomStatus = "ACTIVE"
	RoomStatusINACTIVE         RoomStatus = "INACTIVE"
	RoomStatusUNDERMAINTENANCE RoomStatus = "UNDER_MAINTENANCE"
)

func (e *RoomStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RoomStatus(s)
	case string:
		*e = RoomStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for RoomStatus: %T", src)
	}
	return nil
}

type NullRoomStatus struct {
	RoomStatus RoomStatus `json:"room_status"`
	Valid      bool       `json:"valid"` // Valid is true if RoomStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRoomStatus) Scan(value interface{}) error {
	if value == nil {
		ns.RoomStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RoomStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRoomStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RoomStatus), nil
}

type RoomType string

const (
	RoomTypeLECTUREHALL    RoomType = "LECTURE_HALL"
	RoomTypeLAB            RoomType = "LAB"
	RoomTypeSEMINARROOM    RoomType = "SEMINAR_ROOM"
	RoomTypeAUDITORIUM     RoomType = "AUDITORIUM"
	RoomTypeCONFERENCEROOM RoomType = "CONFERENCE_ROOM"
)

func (e *RoomType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RoomType(s)
	case string:
		*e = RoomType(s)
	default:
		return fmt.Errorf("unsupported scan type for RoomType: %T", src)
	}
	return nil
}

type NullRoomType struct {
	RoomType RoomType `json:"room_type"`
	Valid    bool     `json:"valid"` // Valid is true if RoomType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRoomType) Scan(value interface{}) error {
	if value == nil {
		ns.RoomType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RoomType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRoomType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RoomType), nil
}

type SemesterStatus string

const (
	SemesterStatusDRAFT    SemesterStatus = "DRAFT"
	SemesterStatusACTIVE   SemesterStatus = "ACTIVE"
	SemesterStatusARCHIVED SemesterStatus = "ARCHIVED"
)

func (e *SemesterStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SemesterStatus(s)
	case string:
		*e = SemesterStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for SemesterStatus: %T", src)
	}
	return nil
}

type NullSemesterStatus struct {
	SemesterStatus SemesterStatus `json:"semester_status"`
	Valid          bool           `json:"valid"` // Valid is true if SemesterStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSemesterStatus) Scan(value interface{}) error {
	if value == nil {
		ns.SemesterStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SemesterStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSemesterStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SemesterStatus), nil
}

type UserRole string

const (
	UserRoleSYSTEMADMIN    UserRole = "SYSTEM_ADMIN"
	UserRoleTIMETABLEADMIN UserRole = "TIMETABLE_ADMIN"
	UserRoleBOOKINGOFFICER UserRole = "BOOKING_OFFICER"
	UserRoleREQUESTER      UserRole = "REQUESTER"
)

func (e *UserRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserRole(s)
	case string:
		*e = UserRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UserRole: %T", src)
	}
	return nil
}

type NullUserRole struct {
	UserRole UserRole `json:"user_role"`
	Valid    bool     `json:"valid"` // Valid is true if UserRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserRole) Scan(value interface{}) error {
	if value == nil {
		ns.UserRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserRole), nil
}

type UserStatus string

const (
	UserStatusACTIVE              UserStatus = "ACTIVE"
	UserStatusSUSPENDED           UserStatus = "SUSPENDED"
	UserStatusPENDINGVERIFICATION UserStatus = "PENDING_VERIFICATION"
)

func (e *UserStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserStatus(s)
	case string:
		*e = UserStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for UserStatus: %T", src)
	}
	return nil
}

type NullUserStatus struct {
	UserStatus UserStatus `json:"user_status"`
	Valid      bool       `json:"valid"` // Valid is true if UserStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserStatus) Scan(value interface{}) error {
	if value == nil {
		ns.UserStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserStatus), nil
}

type AuditLog struct {
	ID         uuid.UUID          `json:"id"`
	ActorID    *uuid.UUID         `json:"actor_id"`
	Action     string             `json:"action"`
	EntityType string             `json:"entity_type"`
	EntityID   *uuid.UUID         `json:"entity_id"`
	Changes    []byte             `json:"changes"`
	IpAddress  *string            `json:"ip_address"`
	UserAgent  *string            `json:"user_agent"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type Booking struct {
	ID            uuid.UUID                        `json:"id"`
	RoomID        uuid.UUID                        `json:"room_id"`
	RequestedBy   uuid.UUID                        `json:"requested_by"`
	Purpose       string                           `json:"purpose"`
	AttendeeCount int32                            `json:"attendee_count"`
	StartsAt      pgtype.Timestamptz               `json:"starts_at"`
	EndsAt        pgtype.Timestamptz               `json:"ends_at"`
	Status        BookingStatus                    `json:"status"`
	ReviewedBy    *uuid.UUID                       `json:"reviewed_by"`
	ReviewNote    *string                          `json:"review_note"`
	ReviewedAt    pgtype.Timestamptz               `json:"reviewed_at"`
	CancelledAt   pgtype.Timestamptz               `json:"cancelled_at"`
	During        pgtype.Range[pgtype.Timestamptz] `json:"during"`
	CreatedAt     pgtype.Timestamptz               `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz               `json:"updated_at"`
}

type Building struct {
	ID               uuid.UUID          `json:"id"`
	Code             string             `json:"code"`
	Name             string             `json:"name"`
	Campus           *string            `json:"campus"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	ImageUrl         *string            `json:"image_url"`
	ImagePublicID    *string            `json:"image_public_id"`
	GalleryUrls      []string           `json:"gallery_urls"`
	GalleryPublicIds []string           `json:"gallery_public_ids"`
}

type Course struct {
	ID           uuid.UUID          `json:"id"`
	CourseCode   string             `json:"course_code"`
	Title        string             `json:"title"`
	DepartmentID *uuid.UUID         `json:"department_id"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type Department struct {
	ID        uuid.UUID          `json:"id"`
	Code      string             `json:"code"`
	Name      string             `json:"name"`
	Faculty   *string            `json:"faculty"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Equipment struct {
	ID               uuid.UUID `json:"id"`
	Code             string    `json:"code"`
	Name             string    `json:"name"`
	ImageUrl         *string   `json:"image_url"`
	ImagePublicID    *string   `json:"image_public_id"`
	GalleryUrls      []string  `json:"gallery_urls"`
	GalleryPublicIds []string  `json:"gallery_public_ids"`
}

type IdempotencyKey struct {
	ID           uuid.UUID          `json:"id"`
	UserID       uuid.UUID          `json:"user_id"`
	IdemKey      string             `json:"idem_key"`
	RequestHash  string             `json:"request_hash"`
	StatusCode   int32              `json:"status_code"`
	ResponseBody []byte             `json:"response_body"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	ExpiresAt    pgtype.Timestamptz `json:"expires_at"`
}

type MaintenanceWindow struct {
	ID        uuid.UUID                        `json:"id"`
	RoomID    uuid.UUID                        `json:"room_id"`
	StartsAt  pgtype.Timestamptz               `json:"starts_at"`
	EndsAt    pgtype.Timestamptz               `json:"ends_at"`
	Reason    string                           `json:"reason"`
	CreatedBy uuid.UUID                        `json:"created_by"`
	During    pgtype.Range[pgtype.Timestamptz] `json:"during"`
	CreatedAt pgtype.Timestamptz               `json:"created_at"`
}

type Notification struct {
	ID                uuid.UUID          `json:"id"`
	UserID            uuid.UUID          `json:"user_id"`
	Channel           NotifChannel       `json:"channel"`
	Type              string             `json:"type"`
	Title             string             `json:"title"`
	Body              string             `json:"body"`
	RelatedEntityType *string            `json:"related_entity_type"`
	RelatedEntityID   *uuid.UUID         `json:"related_entity_id"`
	ReadAt            pgtype.Timestamptz `json:"read_at"`
	SentAt            pgtype.Timestamptz `json:"sent_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

type PasswordResetToken struct {
	ID        uuid.UUID          `json:"id"`
	UserID    uuid.UUID          `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	UsedAt    pgtype.Timestamptz `json:"used_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type PushDevice struct {
	ID         uuid.UUID          `json:"id"`
	UserID     uuid.UUID          `json:"user_id"`
	ExpoToken  string             `json:"expo_token"`
	Platform   *string            `json:"platform"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	LastSeenAt pgtype.Timestamptz `json:"last_seen_at"`
}

type RefreshToken struct {
	ID        uuid.UUID          `json:"id"`
	UserID    uuid.UUID          `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	FamilyID  uuid.UUID          `json:"family_id"`
	UserAgent *string            `json:"user_agent"`
	IpAddress *string            `json:"ip_address"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Room struct {
	ID               uuid.UUID          `json:"id"`
	RoomCode         string             `json:"room_code"`
	Name             string             `json:"name"`
	BuildingID       uuid.UUID          `json:"building_id"`
	Capacity         int32              `json:"capacity"`
	RoomType         RoomType           `json:"room_type"`
	Status           RoomStatus         `json:"status"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	ImageUrl         *string            `json:"image_url"`
	ImagePublicID    *string            `json:"image_public_id"`
	GalleryUrls      []string           `json:"gallery_urls"`
	GalleryPublicIds []string           `json:"gallery_public_ids"`
}

type RoomEquipment struct {
	RoomID      uuid.UUID `json:"room_id"`
	EquipmentID uuid.UUID `json:"equipment_id"`
	Quantity    int32     `json:"quantity"`
}

type Semester struct {
	ID        uuid.UUID          `json:"id"`
	Name      string             `json:"name"`
	StartDate pgtype.Date        `json:"start_date"`
	EndDate   pgtype.Date        `json:"end_date"`
	Status    SemesterStatus     `json:"status"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type TimetableEvent struct {
	ID           uuid.UUID          `json:"id"`
	SemesterID   uuid.UUID          `json:"semester_id"`
	ImportID     *uuid.UUID         `json:"import_id"`
	RoomID       uuid.UUID          `json:"room_id"`
	CourseCode   string             `json:"course_code"`
	CourseTitle  string             `json:"course_title"`
	LecturerName string             `json:"lecturer_name"`
	Day          DayOfWeek          `json:"day"`
	StartTime    pgtype.Time        `json:"start_time"`
	EndTime      pgtype.Time        `json:"end_time"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	Section      string             `json:"section"`
	Program      string             `json:"program"`
	Department   string             `json:"department"`
}

type TimetableImport struct {
	ID            uuid.UUID          `json:"id"`
	SemesterID    uuid.UUID          `json:"semester_id"`
	UploadedBy    uuid.UUID          `json:"uploaded_by"`
	Method        ImportMethod       `json:"method"`
	FileObjectKey *string            `json:"file_object_key"`
	Status        ImportStatus       `json:"status"`
	TotalRows     int32              `json:"total_rows"`
	ImportedRows  int32              `json:"imported_rows"`
	ErrorRows     int32              `json:"error_rows"`
	ErrorReport   []byte             `json:"error_report"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	CompletedAt   pgtype.Timestamptz `json:"completed_at"`
}

type User struct {
	ID                  uuid.UUID          `json:"id"`
	Email               string             `json:"email"`
	PasswordHash        string             `json:"password_hash"`
	FullName            string             `json:"full_name"`
	Role                UserRole           `json:"role"`
	DepartmentID        *uuid.UUID         `json:"department_id"`
	Status              UserStatus         `json:"status"`
	MfaEnabled          bool               `json:"mfa_enabled"`
	MfaSecretEncrypted  []byte             `json:"mfa_secret_encrypted"`
	FailedLoginAttempts int32              `json:"failed_login_attempts"`
	LockedUntil         pgtype.Timestamptz `json:"locked_until"`
	LastLoginAt         pgtype.Timestamptz `json:"last_login_at"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	LastMfaTimestep     *int64             `json:"last_mfa_timestep"`
}
