// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notifications.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countUnread = `-- name: CountUnread :one
SELECT count(*) FROM notifications WHERE user_id = $1 AND read_at IS NULL
`

func (q *Queries) CountUnread(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countUnread, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createMaintenanceWindow = `-- name: CreateMaintenanceWindow :one
INSERT INTO maintenance_windows (room_id, starts_at, ends_at, reason, created_by)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, room_id, starts_at, ends_at, reason, created_by, created_at
`

type CreateMaintenanceWindowParams struct {
	RoomID    uuid.UUID          `json:"room_id"`
	StartsAt  pgtype.Timestamptz `json:"starts_at"`
	EndsAt    pgtype.Timestamptz `json:"ends_at"`
	Reason    string             `json:"reason"`
	CreatedBy uuid.UUID          `json:"created_by"`
}

type CreateMaintenanceWindowRow struct {
	ID        uuid.UUID          `json:"id"`
	RoomID    uuid.UUID          `json:"room_id"`
	StartsAt  pgtype.Timestamptz `json:"starts_at"`
	EndsAt    pgtype.Timestamptz `json:"ends_at"`
	Reason    string             `json:"reason"`
	CreatedBy uuid.UUID          `json:"created_by"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

// ── Maintenance windows (§6.6) ────────────────────────────────
func (q *Queries) CreateMaintenanceWindow(ctx context.Context, arg CreateMaintenanceWindowParams) (CreateMaintenanceWindowRow, error) {
	row := q.db.QueryRow(ctx, createMaintenanceWindow,
		arg.RoomID,
		arg.StartsAt,
		arg.EndsAt,
		arg.Reason,
		arg.CreatedBy,
	)
	var i CreateMaintenanceWindowRow
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.StartsAt,
		&i.EndsAt,
		&i.Reason,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const createNotification = `-- name: CreateNotification :one
INSERT INTO notifications (user_id, channel, type, title, body, related_entity_type, related_entity_id, sent_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, user_id, channel, type, title, body, related_entity_type, related_entity_id, read_at, sent_at, created_at
`

type CreateNotificationParams struct {
	UserID            uuid.UUID          `json:"user_id"`
	Channel           NotifChannel       `json:"channel"`
	Type              string             `json:"type"`
	Title             string             `json:"title"`
	Body              string             `json:"body"`
	RelatedEntityType *string            `json:"related_entity_type"`
	RelatedEntityID   *uuid.UUID         `json:"related_entity_id"`
	SentAt            pgtype.Timestamptz `json:"sent_at"`
}

// ── Notifications (§6.8) ───────────────────────────────────────
func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error) {
	row := q.db.QueryRow(ctx, createNotification,
		arg.UserID,
		arg.Channel,
		arg.Type,
		arg.Title,
		arg.Body,
		arg.RelatedEntityType,
		arg.RelatedEntityID,
		arg.SentAt,
	)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Channel,
		&i.Type,
		&i.Title,
		&i.Body,
		&i.RelatedEntityType,
		&i.RelatedEntityID,
		&i.ReadAt,
		&i.SentAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteMaintenanceWindow = `-- name: DeleteMaintenanceWindow :exec
DELETE FROM maintenance_windows WHERE id = $1
`

func (q *Queries) DeleteMaintenanceWindow(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteMaintenanceWindow, id)
	return err
}

const getMaintenanceWindow = `-- name: GetMaintenanceWindow :one
SELECT id, room_id, starts_at, ends_at, reason, created_by, created_at
FROM maintenance_windows WHERE id = $1
`

type GetMaintenanceWindowRow struct {
	ID        uuid.UUID          `json:"id"`
	RoomID    uuid.UUID          `json:"room_id"`
	StartsAt  pgtype.Timestamptz `json:"starts_at"`
	EndsAt    pgtype.Timestamptz `json:"ends_at"`
	Reason    string             `json:"reason"`
	CreatedBy uuid.UUID          `json:"created_by"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetMaintenanceWindow(ctx context.Context, id uuid.UUID) (GetMaintenanceWindowRow, error) {
	row := q.db.QueryRow(ctx, getMaintenanceWindow, id)
	var i GetMaintenanceWindowRow
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.StartsAt,
		&i.EndsAt,
		&i.Reason,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const insertAuditLog = `-- name: InsertAuditLog :exec
INSERT INTO audit_logs (actor_id, action, entity_type, entity_id, changes, ip_address, user_agent)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type InsertAuditLogParams struct {
	ActorID    *uuid.UUID `json:"actor_id"`
	Action     string     `json:"action"`
	EntityType string     `json:"entity_type"`
	EntityID   *uuid.UUID `json:"entity_id"`
	Changes    []byte     `json:"changes"`
	IpAddress  *string    `json:"ip_address"`
	UserAgent  *string    `json:"user_agent"`
}

// ── Audit log (append-only; §6.9) ─────────────────────────────
func (q *Queries) InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) error {
	_, err := q.db.Exec(ctx, insertAuditLog,
		arg.ActorID,
		arg.Action,
		arg.EntityType,
		arg.EntityID,
		arg.Changes,
		arg.IpAddress,
		arg.UserAgent,
	)
	return err
}

const listAuditLogs = `-- name: ListAuditLogs :many
SELECT id, actor_id, action, entity_type, entity_id, changes, ip_address, user_agent, created_at FROM audit_logs
WHERE ($1::uuid IS NULL OR actor_id = $1)
  AND ($2::text IS NULL OR entity_type = $2)
  AND ($3::uuid IS NULL OR entity_id = $3)
  AND ($4::uuid IS NULL OR id < $4)
ORDER BY id DESC
LIMIT $5
`

type ListAuditLogsParams struct {
	ActorID    *uuid.UUID `json:"actor_id"`
	EntityType *string    `json:"entity_type"`
	EntityID   *uuid.UUID `json:"entity_id"`
	Cursor     *uuid.UUID `json:"cursor"`
	Lim        int32      `json:"lim"`
}

func (q *Queries) ListAuditLogs(ctx context.Context, arg ListAuditLogsParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditLogs,
		arg.ActorID,
		arg.EntityType,
		arg.EntityID,
		arg.Cursor,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditLog
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.ActorID,
			&i.Action,
			&i.EntityType,
			&i.EntityID,
			&i.Changes,
			&i.IpAddress,
			&i.UserAgent,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMaintenanceForRoomInRange = `-- name: ListMaintenanceForRoomInRange :many
SELECT id, room_id, starts_at, ends_at, reason, created_by, created_at
FROM maintenance_windows
WHERE room_id = $1
  AND during && tstzrange($2::timestamptz, $3::timestamptz, '[)')
ORDER BY starts_at
`

type ListMaintenanceForRoomInRangeParams struct {
	RoomID   uuid.UUID          `json:"room_id"`
	DayStart pgtype.Timestamptz `json:"day_start"`
	DayEnd   pgtype.Timestamptz `json:"day_end"`
}

type ListMaintenanceForRoomInRangeRow struct {
	ID        uuid.UUID          `json:"id"`
	RoomID    uuid.UUID          `json:"room_id"`
	StartsAt  pgtype.Timestamptz `json:"starts_at"`
	EndsAt    pgtype.Timestamptz `json:"ends_at"`
	Reason    string             `json:"reason"`
	CreatedBy uuid.UUID          `json:"created_by"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

// Maintenance overlapping [day_start, day_end). Availability (§7.1).
func (q *Queries) ListMaintenanceForRoomInRange(ctx context.Context, arg ListMaintenanceForRoomInRangeParams) ([]ListMaintenanceForRoomInRangeRow, error) {
	rows, err := q.db.Query(ctx, listMaintenanceForRoomInRange, arg.RoomID, arg.DayStart, arg.DayEnd)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMaintenanceForRoomInRangeRow
	for rows.Next() {
		var i ListMaintenanceForRoomInRangeRow
		if err := rows.Scan(
			&i.ID,
			&i.RoomID,
			&i.StartsAt,
			&i.EndsAt,
			&i.Reason,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMaintenanceWindows = `-- name: ListMaintenanceWindows :many
SELECT id, room_id, starts_at, ends_at, reason, created_by, created_at
FROM maintenance_windows
WHERE ($1::uuid IS NULL OR room_id = $1)
ORDER BY starts_at DESC
`

type ListMaintenanceWindowsRow struct {
	ID        uuid.UUID          `json:"id"`
	RoomID    uuid.UUID          `json:"room_id"`
	StartsAt  pgtype.Timestamptz `json:"starts_at"`
	EndsAt    pgtype.Timestamptz `json:"ends_at"`
	Reason    string             `json:"reason"`
	CreatedBy uuid.UUID          `json:"created_by"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListMaintenanceWindows(ctx context.Context, roomID *uuid.UUID) ([]ListMaintenanceWindowsRow, error) {
	rows, err := q.db.Query(ctx, listMaintenanceWindows, roomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMaintenanceWindowsRow
	for rows.Next() {
		var i ListMaintenanceWindowsRow
		if err := rows.Scan(
			&i.ID,
			&i.RoomID,
			&i.StartsAt,
			&i.EndsAt,
			&i.Reason,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotifications = `-- name: ListNotifications :many
SELECT id, user_id, channel, type, title, body, related_entity_type, related_entity_id, read_at, sent_at, created_at FROM notifications
WHERE user_id = $1
  AND ($2::boolean = false OR read_at IS NULL)
  AND ($3::uuid IS NULL OR id < $3)
ORDER BY id DESC
LIMIT $4
`

type ListNotificationsParams struct {
	UserID     uuid.UUID  `json:"user_id"`
	UnreadOnly bool       `json:"unread_only"`
	Cursor     *uuid.UUID `json:"cursor"`
	Lim        int32      `json:"lim"`
}

func (q *Queries) ListNotifications(ctx context.Context, arg ListNotificationsParams) ([]Notification, error) {
	rows, err := q.db.Query(ctx, listNotifications,
		arg.UserID,
		arg.UnreadOnly,
		arg.Cursor,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Notification
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Channel,
			&i.Type,
			&i.Title,
			&i.Body,
			&i.RelatedEntityType,
			&i.RelatedEntityID,
			&i.ReadAt,
			&i.SentAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserPushTokens = `-- name: ListUserPushTokens :many
SELECT expo_token FROM push_devices WHERE user_id = $1
`

func (q *Queries) ListUserPushTokens(ctx context.Context, userID uuid.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, listUserPushTokens, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var expo_token string
		if err := rows.Scan(&expo_token); err != nil {
			return nil, err
		}
		items = append(items, expo_token)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAllNotificationsRead = `-- name: MarkAllNotificationsRead :exec
UPDATE notifications SET read_at = now() WHERE user_id = $1 AND read_at IS NULL
`

func (q *Queries) MarkAllNotificationsRead(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, markAllNotificationsRead, userID)
	return err
}

const markNotificationRead = `-- name: MarkNotificationRead :exec
UPDATE notifications SET read_at = now() WHERE id = $1 AND user_id = $2 AND read_at IS NULL
`

type MarkNotificationReadParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) MarkNotificationRead(ctx context.Context, arg MarkNotificationReadParams) error {
	_, err := q.db.Exec(ctx, markNotificationRead, arg.ID, arg.UserID)
	return err
}

const registerPushDevice = `-- name: RegisterPushDevice :one
INSERT INTO push_devices (user_id, expo_token, platform)
VALUES ($1, $2, $3)
ON CONFLICT (expo_token) DO UPDATE SET user_id = EXCLUDED.user_id, last_seen_at = now()
RETURNING id, user_id, expo_token, platform, created_at, last_seen_at
`

type RegisterPushDeviceParams struct {
	UserID    uuid.UUID `json:"user_id"`
	ExpoToken string    `json:"expo_token"`
	Platform  *string   `json:"platform"`
}

// ── Push devices (§13) ────────────────────────────────────────
func (q *Queries) RegisterPushDevice(ctx context.Context, arg RegisterPushDeviceParams) (PushDevice, error) {
	row := q.db.QueryRow(ctx, registerPushDevice, arg.UserID, arg.ExpoToken, arg.Platform)
	var i PushDevice
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ExpoToken,
		&i.Platform,
		&i.CreatedAt,
		&i.LastSeenAt,
	)
	return i, err
}
