// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AddRoomEquipment(ctx context.Context, arg AddRoomEquipmentParams) error
	ClearRoomEquipment(ctx context.Context, roomID uuid.UUID) error
	ConsumePasswordResetToken(ctx context.Context, id uuid.UUID) error
	// Competing PENDING requests for the same room/window (FR8 surfacing).
	CountPendingOverlap(ctx context.Context, arg CountPendingOverlapParams) (int64, error)
	CountUnread(ctx context.Context, userID uuid.UUID) (int64, error)
	// Booking queries. We never SELECT the generated `during` column (a tstzrange);
	// the partial EXCLUDE constraint and the validation trigger are the guarantees.
	CreateBooking(ctx context.Context, arg CreateBookingParams) (CreateBookingRow, error)
	// ── Buildings ─────────────────────────────────────────────────
	CreateBuilding(ctx context.Context, arg CreateBuildingParams) (Building, error)
	// ── Departments ───────────────────────────────────────────────
	CreateDepartment(ctx context.Context, arg CreateDepartmentParams) (Department, error)
	// ── Equipment ─────────────────────────────────────────────────
	CreateEquipment(ctx context.Context, arg CreateEquipmentParams) (Equipment, error)
	// ── Maintenance windows (§6.6) ────────────────────────────────
	CreateMaintenanceWindow(ctx context.Context, arg CreateMaintenanceWindowParams) (CreateMaintenanceWindowRow, error)
	// ── Notifications (§6.8) ───────────────────────────────────────
	CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error)
	// ── Password reset tokens ─────────────────────────────────────
	CreatePasswordResetToken(ctx context.Context, arg CreatePasswordResetTokenParams) (PasswordResetToken, error)
	// ── Refresh tokens (opaque, hashed, rotated; §9.1) ────────────
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error)
	// ── Rooms ─────────────────────────────────────────────────────
	CreateRoom(ctx context.Context, arg CreateRoomParams) (Room, error)
	// ── Semesters ─────────────────────────────────────────────────
	CreateSemester(ctx context.Context, arg CreateSemesterParams) (Semester, error)
	// ── Timetable events ──────────────────────────────────────────
	CreateTimetableEvent(ctx context.Context, arg CreateTimetableEventParams) (TimetableEvent, error)
	// ── Timetable imports ─────────────────────────────────────────
	CreateTimetableImport(ctx context.Context, arg CreateTimetableImportParams) (TimetableImport, error)
	// ── Users ─────────────────────────────────────────────────────
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteBuilding(ctx context.Context, id uuid.UUID) error
	DeleteDepartment(ctx context.Context, id uuid.UUID) error
	DeleteEquipment(ctx context.Context, id uuid.UUID) error
	DeleteExpiredIdempotencyKeys(ctx context.Context) error
	DeleteMaintenanceWindow(ctx context.Context, id uuid.UUID) error
	DeleteSemester(ctx context.Context, id uuid.UUID) error
	DeleteSemesterEvents(ctx context.Context, semesterID uuid.UUID) error
	DeleteTimetableEvent(ctx context.Context, id uuid.UUID) error
	EnableMFA(ctx context.Context, id uuid.UUID) error
	// Set EXPIRED for PENDING bookings whose start time has passed (§7.2).
	ExpireStalePending(ctx context.Context) (int64, error)
	GetActiveSemester(ctx context.Context) (Semester, error)
	GetBooking(ctx context.Context, id uuid.UUID) (GetBookingRow, error)
	// Lock the row for the approval re-check (§7.3).
	GetBookingForUpdate(ctx context.Context, id uuid.UUID) (GetBookingForUpdateRow, error)
	GetBuilding(ctx context.Context, id uuid.UUID) (Building, error)
	GetBuildingByName(ctx context.Context, lower string) (Building, error)
	GetDepartment(ctx context.Context, id uuid.UUID) (Department, error)
	GetEquipment(ctx context.Context, id uuid.UUID) (Equipment, error)
	// ── Idempotency keys (§8.1) ───────────────────────────────────
	GetIdempotencyKey(ctx context.Context, arg GetIdempotencyKeyParams) (IdempotencyKey, error)
	// LOW-8: read the last accepted TOTP timestep for replay detection.
	GetLastMFATimestep(ctx context.Context, id uuid.UUID) (*int64, error)
	GetMaintenanceWindow(ctx context.Context, id uuid.UUID) (GetMaintenanceWindowRow, error)
	GetPasswordResetToken(ctx context.Context, tokenHash string) (PasswordResetToken, error)
	GetRefreshTokenByHash(ctx context.Context, tokenHash string) (RefreshToken, error)
	GetRoom(ctx context.Context, id uuid.UUID) (Room, error)
	GetRoomByCode(ctx context.Context, roomCode string) (Room, error)
	GetRoomByName(ctx context.Context, lower string) (Room, error)
	GetSemester(ctx context.Context, id uuid.UUID) (Semester, error)
	GetTimetableEvent(ctx context.Context, id uuid.UUID) (TimetableEvent, error)
	GetTimetableImport(ctx context.Context, id uuid.UUID) (TimetableImport, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	// ── Audit log (append-only; §6.9) ─────────────────────────────
	InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) error
	// Approved bookings whose time overlaps [day_start, day_end). Availability (§7.1, BR5).
	ListApprovedBookingsForRoomInRange(ctx context.Context, arg ListApprovedBookingsForRoomInRangeParams) ([]ListApprovedBookingsForRoomInRangeRow, error)
	ListAuditLogs(ctx context.Context, arg ListAuditLogsParams) ([]ListAuditLogsRow, error)
	ListBookings(ctx context.Context, arg ListBookingsParams) ([]ListBookingsRow, error)
	ListBuildings(ctx context.Context) ([]Building, error)
	// Other approved bookings overlapping the given window for a room (override support, BR6).
	ListConflictingApprovedBookings(ctx context.Context, arg ListConflictingApprovedBookingsParams) ([]ListConflictingApprovedBookingsRow, error)
	ListCourses(ctx context.Context) ([]Course, error)
	ListDepartments(ctx context.Context) ([]Department, error)
	ListEquipment(ctx context.Context) ([]Equipment, error)
	// Maintenance overlapping [day_start, day_end). Availability (§7.1).
	ListMaintenanceForRoomInRange(ctx context.Context, arg ListMaintenanceForRoomInRangeParams) ([]ListMaintenanceForRoomInRangeRow, error)
	ListMaintenanceWindows(ctx context.Context, roomID *uuid.UUID) ([]ListMaintenanceWindowsRow, error)
	ListNotifications(ctx context.Context, arg ListNotificationsParams) ([]Notification, error)
	// Pending bookings enriched with room + requester (+ department) for the
	// approvals queue (FR8, §11). Joined here so the handler avoids N+1 lookups; the
	// approvability blockers are then computed per row in the service layer.
	ListPendingForApproval(ctx context.Context, arg ListPendingForApprovalParams) ([]ListPendingForApprovalRow, error)
	ListRoomEquipment(ctx context.Context, roomID uuid.UUID) ([]ListRoomEquipmentRow, error)
	// Active-semester lectures for a room on a given weekday, where the date falls
	// inside the semester window. Used by the availability engine (§7.1, BR1/BR2).
	ListRoomLecturesOnDay(ctx context.Context, arg ListRoomLecturesOnDayParams) ([]ListRoomLecturesOnDayRow, error)
	ListSemesters(ctx context.Context) ([]Semester, error)
	ListTimetableEvents(ctx context.Context, arg ListTimetableEventsParams) ([]TimetableEvent, error)
	ListUserPushTokens(ctx context.Context, userID uuid.UUID) ([]string, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	MarkAllNotificationsRead(ctx context.Context, userID uuid.UUID) error
	MarkNotificationRead(ctx context.Context, arg MarkNotificationReadParams) error
	PutIdempotencyKey(ctx context.Context, arg PutIdempotencyKeyParams) (IdempotencyKey, error)
	RecordFailedLogin(ctx context.Context, arg RecordFailedLoginParams) (RecordFailedLoginRow, error)
	RecordSuccessfulLogin(ctx context.Context, id uuid.UUID) error
	// ── Push devices (§13) ────────────────────────────────────────
	RegisterPushDevice(ctx context.Context, arg RegisterPushDeviceParams) (PushDevice, error)
	RevokeAllUserRefreshTokens(ctx context.Context, userID uuid.UUID) error
	RevokeRefreshFamily(ctx context.Context, familyID uuid.UUID) error
	RevokeRefreshToken(ctx context.Context, id uuid.UUID) error
	// Generic status transition used by approve/reject/cancel/override/expire.
	SetBookingStatus(ctx context.Context, arg SetBookingStatusParams) (SetBookingStatusRow, error)
	// LOW-8: persist the accepted TOTP timestep so an earlier/equal one is rejected.
	SetLastMFATimestep(ctx context.Context, arg SetLastMFATimestepParams) error
	SetMFASecret(ctx context.Context, arg SetMFASecretParams) error
	SetRoomStatus(ctx context.Context, arg SetRoomStatusParams) (Room, error)
	SetSemesterStatus(ctx context.Context, arg SetSemesterStatusParams) (Semester, error)
	SetUserStatus(ctx context.Context, arg SetUserStatusParams) (User, error)
	UpdateBuilding(ctx context.Context, arg UpdateBuildingParams) (Building, error)
	UpdateBuildingImages(ctx context.Context, arg UpdateBuildingImagesParams) (Building, error)
	UpdateDepartment(ctx context.Context, arg UpdateDepartmentParams) (Department, error)
	UpdateEquipment(ctx context.Context, arg UpdateEquipmentParams) (Equipment, error)
	UpdateEquipmentImages(ctx context.Context, arg UpdateEquipmentImagesParams) (Equipment, error)
	UpdateImportProgress(ctx context.Context, arg UpdateImportProgressParams) (TimetableImport, error)
	UpdatePasswordHash(ctx context.Context, arg UpdatePasswordHashParams) error
	UpdateRoom(ctx context.Context, arg UpdateRoomParams) (Room, error)
	UpdateRoomImages(ctx context.Context, arg UpdateRoomImagesParams) (Room, error)
	UpdateSemester(ctx context.Context, arg UpdateSemesterParams) (Semester, error)
	UpdateTimetableEvent(ctx context.Context, arg UpdateTimetableEventParams) (TimetableEvent, error)
	UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error)
	UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) (User, error)
	// ── Courses ───────────────────────────────────────────────────
	UpsertCourse(ctx context.Context, arg UpsertCourseParams) (Course, error)
}

var _ Querier = (*Queries)(nil)
