// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: scheduling.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createSemester = `-- name: CreateSemester :one
INSERT INTO semesters (name, start_date, end_date, status)
VALUES ($1, $2, $3, $4) RETURNING id, name, start_date, end_date, status, created_at, updated_at
`

type CreateSemesterParams struct {
	Name      string         `json:"name"`
	StartDate pgtype.Date    `json:"start_date"`
	EndDate   pgtype.Date    `json:"end_date"`
	Status    SemesterStatus `json:"status"`
}

// ── Semesters ─────────────────────────────────────────────────
func (q *Queries) CreateSemester(ctx context.Context, arg CreateSemesterParams) (Semester, error) {
	row := q.db.QueryRow(ctx, createSemester,
		arg.Name,
		arg.StartDate,
		arg.EndDate,
		arg.Status,
	)
	var i Semester
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.StartDate,
		&i.EndDate,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTimetableEvent = `-- name: CreateTimetableEvent :one
INSERT INTO timetable_events
  (semester_id, import_id, room_id, course_code, course_title, lecturer_name, day, start_time, end_time)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, semester_id, import_id, room_id, course_code, course_title, lecturer_name, day, start_time, end_time, created_at
`

type CreateTimetableEventParams struct {
	SemesterID   uuid.UUID   `json:"semester_id"`
	ImportID     *uuid.UUID  `json:"import_id"`
	RoomID       uuid.UUID   `json:"room_id"`
	CourseCode   string      `json:"course_code"`
	CourseTitle  string      `json:"course_title"`
	LecturerName string      `json:"lecturer_name"`
	Day          DayOfWeek   `json:"day"`
	StartTime    pgtype.Time `json:"start_time"`
	EndTime      pgtype.Time `json:"end_time"`
}

// ── Timetable events ──────────────────────────────────────────
func (q *Queries) CreateTimetableEvent(ctx context.Context, arg CreateTimetableEventParams) (TimetableEvent, error) {
	row := q.db.QueryRow(ctx, createTimetableEvent,
		arg.SemesterID,
		arg.ImportID,
		arg.RoomID,
		arg.CourseCode,
		arg.CourseTitle,
		arg.LecturerName,
		arg.Day,
		arg.StartTime,
		arg.EndTime,
	)
	var i TimetableEvent
	err := row.Scan(
		&i.ID,
		&i.SemesterID,
		&i.ImportID,
		&i.RoomID,
		&i.CourseCode,
		&i.CourseTitle,
		&i.LecturerName,
		&i.Day,
		&i.StartTime,
		&i.EndTime,
		&i.CreatedAt,
	)
	return i, err
}

const createTimetableImport = `-- name: CreateTimetableImport :one
INSERT INTO timetable_imports (semester_id, uploaded_by, method, file_object_key, status)
VALUES ($1, $2, $3, $4, 'PENDING') RETURNING id, semester_id, uploaded_by, method, file_object_key, status, total_rows, imported_rows, error_rows, error_report, created_at, completed_at
`

type CreateTimetableImportParams struct {
	SemesterID    uuid.UUID    `json:"semester_id"`
	UploadedBy    uuid.UUID    `json:"uploaded_by"`
	Method        ImportMethod `json:"method"`
	FileObjectKey *string      `json:"file_object_key"`
}

// ── Timetable imports ─────────────────────────────────────────
func (q *Queries) CreateTimetableImport(ctx context.Context, arg CreateTimetableImportParams) (TimetableImport, error) {
	row := q.db.QueryRow(ctx, createTimetableImport,
		arg.SemesterID,
		arg.UploadedBy,
		arg.Method,
		arg.FileObjectKey,
	)
	var i TimetableImport
	err := row.Scan(
		&i.ID,
		&i.SemesterID,
		&i.UploadedBy,
		&i.Method,
		&i.FileObjectKey,
		&i.Status,
		&i.TotalRows,
		&i.ImportedRows,
		&i.ErrorRows,
		&i.ErrorReport,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const deleteSemester = `-- name: DeleteSemester :exec
DELETE FROM semesters WHERE id = $1
`

func (q *Queries) DeleteSemester(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteSemester, id)
	return err
}

const deleteSemesterEvents = `-- name: DeleteSemesterEvents :exec
DELETE FROM timetable_events WHERE semester_id = $1
`

func (q *Queries) DeleteSemesterEvents(ctx context.Context, semesterID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteSemesterEvents, semesterID)
	return err
}

const deleteTimetableEvent = `-- name: DeleteTimetableEvent :exec
DELETE FROM timetable_events WHERE id = $1
`

func (q *Queries) DeleteTimetableEvent(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteTimetableEvent, id)
	return err
}

const getActiveSemester = `-- name: GetActiveSemester :one
SELECT id, name, start_date, end_date, status, created_at, updated_at FROM semesters WHERE status = 'ACTIVE'
`

func (q *Queries) GetActiveSemester(ctx context.Context) (Semester, error) {
	row := q.db.QueryRow(ctx, getActiveSemester)
	var i Semester
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.StartDate,
		&i.EndDate,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSemester = `-- name: GetSemester :one
SELECT id, name, start_date, end_date, status, created_at, updated_at FROM semesters WHERE id = $1
`

func (q *Queries) GetSemester(ctx context.Context, id uuid.UUID) (Semester, error) {
	row := q.db.QueryRow(ctx, getSemester, id)
	var i Semester
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.StartDate,
		&i.EndDate,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTimetableEvent = `-- name: GetTimetableEvent :one
SELECT id, semester_id, import_id, room_id, course_code, course_title, lecturer_name, day, start_time, end_time, created_at FROM timetable_events WHERE id = $1
`

func (q *Queries) GetTimetableEvent(ctx context.Context, id uuid.UUID) (TimetableEvent, error) {
	row := q.db.QueryRow(ctx, getTimetableEvent, id)
	var i TimetableEvent
	err := row.Scan(
		&i.ID,
		&i.SemesterID,
		&i.ImportID,
		&i.RoomID,
		&i.CourseCode,
		&i.CourseTitle,
		&i.LecturerName,
		&i.Day,
		&i.StartTime,
		&i.EndTime,
		&i.CreatedAt,
	)
	return i, err
}

const getTimetableImport = `-- name: GetTimetableImport :one
SELECT id, semester_id, uploaded_by, method, file_object_key, status, total_rows, imported_rows, error_rows, error_report, created_at, completed_at FROM timetable_imports WHERE id = $1
`

func (q *Queries) GetTimetableImport(ctx context.Context, id uuid.UUID) (TimetableImport, error) {
	row := q.db.QueryRow(ctx, getTimetableImport, id)
	var i TimetableImport
	err := row.Scan(
		&i.ID,
		&i.SemesterID,
		&i.UploadedBy,
		&i.Method,
		&i.FileObjectKey,
		&i.Status,
		&i.TotalRows,
		&i.ImportedRows,
		&i.ErrorRows,
		&i.ErrorReport,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const listCourses = `-- name: ListCourses :many
SELECT id, course_code, title, department_id, created_at FROM courses ORDER BY course_code
`

func (q *Queries) ListCourses(ctx context.Context) ([]Course, error) {
	rows, err := q.db.Query(ctx, listCourses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Course
	for rows.Next() {
		var i Course
		if err := rows.Scan(
			&i.ID,
			&i.CourseCode,
			&i.Title,
			&i.DepartmentID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoomLecturesOnDay = `-- name: ListRoomLecturesOnDay :many
SELECT te.id, te.course_code, te.course_title, te.lecturer_name,
       te.day, te.start_time, te.end_time
FROM timetable_events te
JOIN semesters s ON s.id = te.semester_id AND s.status = 'ACTIVE'
WHERE te.room_id = $1
  AND te.day = $2
  AND $3::date BETWEEN s.start_date AND s.end_date
ORDER BY te.start_time
`

type ListRoomLecturesOnDayParams struct {
	RoomID uuid.UUID   `json:"room_id"`
	Day    DayOfWeek   `json:"day"`
	OnDate pgtype.Date `json:"on_date"`
}

type ListRoomLecturesOnDayRow struct {
	ID           uuid.UUID   `json:"id"`
	CourseCode   string      `json:"course_code"`
	CourseTitle  string      `json:"course_title"`
	LecturerName string      `json:"lecturer_name"`
	Day          DayOfWeek   `json:"day"`
	StartTime    pgtype.Time `json:"start_time"`
	EndTime      pgtype.Time `json:"end_time"`
}

// Active-semester lectures for a room on a given weekday, where the date falls
// inside the semester window. Used by the availability engine (§7.1, BR1/BR2).
func (q *Queries) ListRoomLecturesOnDay(ctx context.Context, arg ListRoomLecturesOnDayParams) ([]ListRoomLecturesOnDayRow, error) {
	rows, err := q.db.Query(ctx, listRoomLecturesOnDay, arg.RoomID, arg.Day, arg.OnDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRoomLecturesOnDayRow
	for rows.Next() {
		var i ListRoomLecturesOnDayRow
		if err := rows.Scan(
			&i.ID,
			&i.CourseCode,
			&i.CourseTitle,
			&i.LecturerName,
			&i.Day,
			&i.StartTime,
			&i.EndTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSemesters = `-- name: ListSemesters :many
SELECT id, name, start_date, end_date, status, created_at, updated_at FROM semesters ORDER BY start_date DESC
`

func (q *Queries) ListSemesters(ctx context.Context) ([]Semester, error) {
	rows, err := q.db.Query(ctx, listSemesters)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Semester
	for rows.Next() {
		var i Semester
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.StartDate,
			&i.EndDate,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTimetableEvents = `-- name: ListTimetableEvents :many
SELECT id, semester_id, import_id, room_id, course_code, course_title, lecturer_name, day, start_time, end_time, created_at FROM timetable_events
WHERE ($1::uuid IS NULL OR semester_id = $1)
  AND ($2::uuid IS NULL OR room_id = $2)
  AND ($3::day_of_week IS NULL OR day = $3)
ORDER BY day, start_time
`

type ListTimetableEventsParams struct {
	SemesterID *uuid.UUID `json:"semester_id"`
	RoomID     *uuid.UUID `json:"room_id"`
	Day        *DayOfWeek `json:"day"`
}

func (q *Queries) ListTimetableEvents(ctx context.Context, arg ListTimetableEventsParams) ([]TimetableEvent, error) {
	rows, err := q.db.Query(ctx, listTimetableEvents, arg.SemesterID, arg.RoomID, arg.Day)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TimetableEvent
	for rows.Next() {
		var i TimetableEvent
		if err := rows.Scan(
			&i.ID,
			&i.SemesterID,
			&i.ImportID,
			&i.RoomID,
			&i.CourseCode,
			&i.CourseTitle,
			&i.LecturerName,
			&i.Day,
			&i.StartTime,
			&i.EndTime,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setSemesterStatus = `-- name: SetSemesterStatus :one
UPDATE semesters SET status = $2, updated_at = now() WHERE id = $1 RETURNING id, name, start_date, end_date, status, created_at, updated_at
`

type SetSemesterStatusParams struct {
	ID     uuid.UUID      `json:"id"`
	Status SemesterStatus `json:"status"`
}

func (q *Queries) SetSemesterStatus(ctx context.Context, arg SetSemesterStatusParams) (Semester, error) {
	row := q.db.QueryRow(ctx, setSemesterStatus, arg.ID, arg.Status)
	var i Semester
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.StartDate,
		&i.EndDate,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateImportProgress = `-- name: UpdateImportProgress :one
UPDATE timetable_imports
SET status = $2, total_rows = $3, imported_rows = $4, error_rows = $5,
    error_report = $6, completed_at = $7
WHERE id = $1 RETURNING id, semester_id, uploaded_by, method, file_object_key, status, total_rows, imported_rows, error_rows, error_report, created_at, completed_at
`

type UpdateImportProgressParams struct {
	ID           uuid.UUID          `json:"id"`
	Status       ImportStatus       `json:"status"`
	TotalRows    int32              `json:"total_rows"`
	ImportedRows int32              `json:"imported_rows"`
	ErrorRows    int32              `json:"error_rows"`
	ErrorReport  []byte             `json:"error_report"`
	CompletedAt  pgtype.Timestamptz `json:"completed_at"`
}

func (q *Queries) UpdateImportProgress(ctx context.Context, arg UpdateImportProgressParams) (TimetableImport, error) {
	row := q.db.QueryRow(ctx, updateImportProgress,
		arg.ID,
		arg.Status,
		arg.TotalRows,
		arg.ImportedRows,
		arg.ErrorRows,
		arg.ErrorReport,
		arg.CompletedAt,
	)
	var i TimetableImport
	err := row.Scan(
		&i.ID,
		&i.SemesterID,
		&i.UploadedBy,
		&i.Method,
		&i.FileObjectKey,
		&i.Status,
		&i.TotalRows,
		&i.ImportedRows,
		&i.ErrorRows,
		&i.ErrorReport,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const updateSemester = `-- name: UpdateSemester :one
UPDATE semesters SET name = $2, start_date = $3, end_date = $4, updated_at = now()
WHERE id = $1 RETURNING id, name, start_date, end_date, status, created_at, updated_at
`

type UpdateSemesterParams struct {
	ID        uuid.UUID   `json:"id"`
	Name      string      `json:"name"`
	StartDate pgtype.Date `json:"start_date"`
	EndDate   pgtype.Date `json:"end_date"`
}

func (q *Queries) UpdateSemester(ctx context.Context, arg UpdateSemesterParams) (Semester, error) {
	row := q.db.QueryRow(ctx, updateSemester,
		arg.ID,
		arg.Name,
		arg.StartDate,
		arg.EndDate,
	)
	var i Semester
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.StartDate,
		&i.EndDate,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTimetableEvent = `-- name: UpdateTimetableEvent :one
UPDATE timetable_events
SET room_id = $2, course_code = $3, course_title = $4, lecturer_name = $5,
    day = $6, start_time = $7, end_time = $8
WHERE id = $1 RETURNING id, semester_id, import_id, room_id, course_code, course_title, lecturer_name, day, start_time, end_time, created_at
`

type UpdateTimetableEventParams struct {
	ID           uuid.UUID   `json:"id"`
	RoomID       uuid.UUID   `json:"room_id"`
	CourseCode   string      `json:"course_code"`
	CourseTitle  string      `json:"course_title"`
	LecturerName string      `json:"lecturer_name"`
	Day          DayOfWeek   `json:"day"`
	StartTime    pgtype.Time `json:"start_time"`
	EndTime      pgtype.Time `json:"end_time"`
}

func (q *Queries) UpdateTimetableEvent(ctx context.Context, arg UpdateTimetableEventParams) (TimetableEvent, error) {
	row := q.db.QueryRow(ctx, updateTimetableEvent,
		arg.ID,
		arg.RoomID,
		arg.CourseCode,
		arg.CourseTitle,
		arg.LecturerName,
		arg.Day,
		arg.StartTime,
		arg.EndTime,
	)
	var i TimetableEvent
	err := row.Scan(
		&i.ID,
		&i.SemesterID,
		&i.ImportID,
		&i.RoomID,
		&i.CourseCode,
		&i.CourseTitle,
		&i.LecturerName,
		&i.Day,
		&i.StartTime,
		&i.EndTime,
		&i.CreatedAt,
	)
	return i, err
}

const upsertCourse = `-- name: UpsertCourse :one
INSERT INTO courses (course_code, title, department_id)
VALUES ($1, $2, $3)
ON CONFLICT (course_code) DO UPDATE SET title = EXCLUDED.title
RETURNING id, course_code, title, department_id, created_at
`

type UpsertCourseParams struct {
	CourseCode   string     `json:"course_code"`
	Title        string     `json:"title"`
	DepartmentID *uuid.UUID `json:"department_id"`
}

// ── Courses ───────────────────────────────────────────────────
func (q *Queries) UpsertCourse(ctx context.Context, arg UpsertCourseParams) (Course, error) {
	row := q.db.QueryRow(ctx, upsertCourse, arg.CourseCode, arg.Title, arg.DepartmentID)
	var i Course
	err := row.Scan(
		&i.ID,
		&i.CourseCode,
		&i.Title,
		&i.DepartmentID,
		&i.CreatedAt,
	)
	return i, err
}
