{{- if and .Values.worker.enabled .Values.worker.pdb.enabled -}}
{{- $component := "worker" -}}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "cbs.fullname" . }}-worker
  labels:
    {{- include "cbs.componentLabels" (merge (dict "component" $component) .) | nindent 4 }}
spec:
  minAvailable: {{ .Values.worker.pdb.minAvailable }}
  selector:
    matchLabels:
      {{- include "cbs.componentSelectorLabels" (merge (dict "component" $component) .) | nindent 6 }}
{{- end }}
