// Flat ESLint config (§17) — extends the shared base from @cbs/config.
// `src/schema.gen.ts` is auto-generated by openapi-typescript and must not be
// linted (the base already ignores `**/*.gen.ts`; repeated here for clarity).
import base from "@cbs/config/eslint/base.js";

/** @type {import("eslint").Linter.Config[]} */
export default [
  ...base,
  {
    ignores: ["dist/**", "node_modules/**", "src/schema.gen.ts", "**/*.gen.ts"],
  },
];
